create table if not exists tags (
    id bigint generated by default as identity primary key,
    tag_type varchar(32) not null,
    parent_id bigint null,
    code varchar(64) not null,
    name varchar(64) not null,
    description varchar(255) null,
    sort_order integer not null default 0,
    enabled boolean not null default true,
    deleted boolean not null default false,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,

    constraint uq_tags_code unique (code),
    constraint ck_tags_type check (tag_type in ('SCENE', 'FUNCTION', 'GENRE')),
    constraint ck_tags_parent_not_self check (parent_id is null or parent_id <> id)
);

comment on table tags is '标签表';
comment on column tags.id is '主键ID';
comment on column tags.tag_type is '标签类型：SCENE=场景标签，FUNCTION=功能标签，GENRE=文章体裁标签';
comment on column tags.parent_id is '父标签ID，用于一级、二级标签层级关系，由代码维护有效性';
comment on column tags.code is '标签编码，供后端和AI稳定识别使用';
comment on column tags.name is '标签中文名称';
comment on column tags.description is '标签说明';
comment on column tags.sort_order is '排序值，数值越小越靠前';
comment on column tags.enabled is '是否启用';
comment on column tags.deleted is '是否删除';
comment on column tags.created_at is '创建时间';
comment on column tags.updated_at is '更新时间';

create index if not exists idx_tags_type on tags (tag_type);
create index if not exists idx_tags_parent_id on tags (parent_id);
create index if not exists idx_tags_enabled_deleted on tags (enabled, deleted);

create table if not exists question_tags (
    id bigint generated by default as identity primary key,
    question_id bigint not null,
    tag_id bigint not null,
    created_at timestamp not null default current_timestamp,

    constraint uq_question_tags_question_id_tag_id unique (question_id, tag_id)
);

comment on table question_tags is '题目标签关联表';
comment on column question_tags.id is '主键ID';
comment on column question_tags.question_id is '题目ID，对应 questions.id，由代码维护有效性';
comment on column question_tags.tag_id is '标签ID，对应 tags.id，由代码维护有效性';
comment on column question_tags.created_at is '创建时间';

create index if not exists idx_question_tags_question_id on question_tags (question_id);
create index if not exists idx_question_tags_tag_id on question_tags (tag_id);

create extension if not exists vector;

create table if not exists questions (
    id bigint generated by default as identity primary key,
    question_type varchar(32) not null default 'TRANSLATION_ZH_TO_JA',
    source_text text not null,
    context_text text null,
    level varchar(8) null,
    difficulty smallint not null default 3,
    grammar_point varchar(255) null,
    spoken boolean not null default false,
    business boolean not null default false,
    exam boolean not null default false,
    source_type varchar(32) not null default 'AI',
    enabled boolean not null default true,
    deleted boolean not null default false,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,

    constraint ck_questions_type check (question_type in ('TRANSLATION_ZH_TO_JA', 'TRANSLATION_ZH_TO_JA_ARTICLE')),
    constraint ck_questions_level check (level is null or level in ('N5', 'N4', 'N3', 'N2', 'N1')),
    constraint ck_questions_difficulty check (difficulty between 1 and 5),
    constraint ck_questions_source_type check (source_type in ('AI', 'MANUAL', 'REVIEW_DERIVED'))
);

comment on table questions is '题目表';
comment on column questions.id is '主键ID';
comment on column questions.question_type is '题目类型：TRANSLATION_ZH_TO_JA=中译日短句，TRANSLATION_ZH_TO_JA_ARTICLE=中译日文章';
comment on column questions.source_text is '中文题目原文，文章题按句使用双换行分隔';
comment on column questions.context_text is '题目语境说明';
comment on column questions.level is 'JLPT等级：N5、N4、N3、N2、N1';
comment on column questions.difficulty is '难度等级，范围1到5';
comment on column questions.grammar_point is '短句语法点或文章生词提示';
comment on column questions.spoken is '是否口语表达';
comment on column questions.business is '是否商务表达';
comment on column questions.exam is '是否考试相关';
comment on column questions.source_type is '题目来源：AI=AI生成，MANUAL=人工录入，REVIEW_DERIVED=复习衍生题';
comment on column questions.enabled is '是否启用';
comment on column questions.deleted is '是否删除';
comment on column questions.created_at is '创建时间';
comment on column questions.updated_at is '更新时间';

create index if not exists idx_questions_type on questions (question_type);
create index if not exists idx_questions_level on questions (level);
create index if not exists idx_questions_difficulty on questions (difficulty);
create index if not exists idx_questions_source_type on questions (source_type);
create index if not exists idx_questions_enabled_deleted on questions (enabled, deleted);

create table if not exists question_embeddings (
    question_id bigint primary key references questions(id),
    embedding vector(768) not null,
    content_hash char(64) not null,
    model_name varchar(128) not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

comment on table question_embeddings is '题目语义向量表，仅用于常规题生成去重';
comment on column question_embeddings.question_id is '题目ID';
comment on column question_embeddings.embedding is '768维语义向量';
comment on column question_embeddings.content_hash is '向量输入内容哈希，文章仅使用正文，短句使用原文和语境';
comment on column question_embeddings.model_name is '嵌入模型名称';

create index if not exists idx_question_embeddings_embedding_hnsw
    on question_embeddings using hnsw (embedding vector_cosine_ops);

create table if not exists article_generation_metadata (
    question_id bigint primary key references questions(id),
    seed uuid not null unique,
    blueprint jsonb not null,
    created_at timestamp not null default current_timestamp,
    constraint ck_article_generation_metadata_blueprint check (
        jsonb_typeof(blueprint) = 'object'
        and blueprint ? 'coreConcept'
        and jsonb_typeof(blueprint -> 'roles') = 'object'
    )
);

comment on table article_generation_metadata is 'AI文章生成蓝图元数据表';
comment on column article_generation_metadata.question_id is '文章题目ID，与questions一对一';
comment on column article_generation_metadata.seed is '最终成功尝试使用的随机UUID种子';
comment on column article_generation_metadata.blueprint is '最终成功生成的核心概念和语义角色';

create table if not exists question_answers (
    id bigint generated by default as identity primary key,
    question_id bigint not null,
    answer_text text not null,
    answer_type varchar(32) not null default 'STANDARD',
    primary_answer boolean not null default false,
    sort_order integer not null default 0,
    deleted boolean not null default false,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,

    constraint ck_question_answers_type check (answer_type in ('STANDARD', 'REFERENCE'))
);

comment on table question_answers is '题目答案表';
comment on column question_answers.id is '主键ID';
comment on column question_answers.question_id is '题目ID，对应 questions.id，由代码维护有效性';
comment on column question_answers.answer_text is '答案文本，当前为日语表达';
comment on column question_answers.answer_type is '答案类型：STANDARD=标准答案，REFERENCE=参考答案';
comment on column question_answers.primary_answer is '是否主答案';
comment on column question_answers.sort_order is '排序值，数值越小越靠前';
comment on column question_answers.deleted is '是否删除';
comment on column question_answers.created_at is '创建时间';
comment on column question_answers.updated_at is '更新时间';

create index if not exists idx_question_answers_question_id on question_answers (question_id);
create index if not exists idx_question_answers_deleted on question_answers (deleted);
create unique index if not exists uq_question_answers_primary
    on question_answers (question_id)
    where primary_answer = true and deleted = false;
create unique index if not exists uq_question_answers_active_text
    on question_answers (question_id, answer_text)
    where deleted = false;

create table if not exists users (
    id bigint generated by default as identity primary key,
    user_code varchar(64) not null,
    nickname varchar(64) not null,
    user_type varchar(32) not null default 'LOCAL',
    enabled boolean not null default true,
    deleted boolean not null default false,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,

    constraint uq_users_user_code unique (user_code),
    constraint ck_users_user_type check (user_type in ('LOCAL', 'REGISTERED')),
    constraint ck_users_user_code_not_blank check (length(trim(user_code)) > 0),
    constraint ck_users_nickname_not_blank check (length(trim(nickname)) > 0)
);

comment on table users is '用户表';
comment on column users.id is '主键ID';
comment on column users.user_code is '用户编码，本地用户或后续账号用户的稳定标识';
comment on column users.nickname is '用户昵称';
comment on column users.user_type is '用户类型：LOCAL=本地用户，REGISTERED=注册用户';
comment on column users.enabled is '是否启用';
comment on column users.deleted is '是否删除';
comment on column users.created_at is '创建时间';
comment on column users.updated_at is '更新时间';

create index if not exists idx_users_user_type on users (user_type);
create index if not exists idx_users_enabled_deleted on users (enabled, deleted);



create table if not exists user_answers (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    question_id bigint null,
    answer_text text not null,
    answer_status varchar(32) not null default 'SUBMITTED',
    grammar_vocabulary_score smallint null,
    natural_fluency_score smallint null,
    scenario_adaptation_score smallint null,
    information_completeness_score smallint null,
    total_score numeric(5, 2) null,
    ai_overall_comment text null,
    ai_revised_text text null,
    deleted boolean not null default false,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,

    constraint ck_user_answers_status check (answer_status in ('SUBMITTED', 'REVIEWED', 'FAILED')),
    constraint ck_user_answers_answer_text_not_blank check (length(trim(answer_text)) > 0),
    constraint ck_user_answers_grammar_vocabulary_score check (
        grammar_vocabulary_score is null or grammar_vocabulary_score between 0 and 100
    ),
    constraint ck_user_answers_natural_fluency_score check (
        natural_fluency_score is null or natural_fluency_score between 0 and 100
    ),
    constraint ck_user_answers_scenario_adaptation_score check (
        scenario_adaptation_score is null or scenario_adaptation_score between 0 and 100
    ),
    constraint ck_user_answers_information_completeness_score check (
        information_completeness_score is null or information_completeness_score between 0 and 100
    ),
    constraint ck_user_answers_total_score check (
        total_score is null or total_score between 0 and 100
    ),
    constraint ck_user_answers_question_or_correction check (
        question_id is not null or ai_revised_text is not null
    )
);

comment on table user_answers is '用户回答表';
comment on column user_answers.id is '主键ID';
comment on column user_answers.user_id is '用户ID，对应 users.id，由代码维护有效性';
comment on column user_answers.question_id is '题目ID，对应 questions.id，由代码维护有效性；纯日语纠错记录为空';
comment on column user_answers.answer_text is '用户提交的日语答案';
comment on column user_answers.answer_status is '回答状态：SUBMITTED=已提交，REVIEWED=已评测，FAILED=评测失败';
comment on column user_answers.grammar_vocabulary_score is '语法与词汇正确性评分，满分100分';
comment on column user_answers.natural_fluency_score is '自然度与流畅度评分，满分100分';
comment on column user_answers.scenario_adaptation_score is '场景适配度评分，满分100分';
comment on column user_answers.information_completeness_score is '表达信息完整性评分，满分100分';
comment on column user_answers.total_score is '总分，四项评分均值，由代码计算';
comment on column user_answers.ai_overall_comment is 'AI总体评价';
comment on column user_answers.ai_revised_text is 'AI修订后的完整日语文本，纯日语纠错记录使用';
comment on column user_answers.deleted is '是否删除';
comment on column user_answers.created_at is '创建时间';
comment on column user_answers.updated_at is '更新时间';

create index if not exists idx_user_answers_user_id on user_answers (user_id);
create index if not exists idx_user_answers_question_id on user_answers (question_id);
create index if not exists idx_user_answers_user_question on user_answers (user_id, question_id);
create index if not exists idx_user_answers_status on user_answers (answer_status);
create index if not exists idx_user_answers_total_score on user_answers (total_score);
create index if not exists idx_user_answers_created_at on user_answers (created_at);
create index if not exists idx_user_answers_deleted on user_answers (deleted);
create index if not exists idx_user_answers_user_created_at_active
    on user_answers (user_id, created_at)
    where deleted = false;

create table if not exists error_types (
    id bigint generated by default as identity primary key,
    parent_id bigint null,
    type_level smallint not null,
    code varchar(64) not null,
    name varchar(64) not null,
    description varchar(255) null,
    sort_order integer not null default 0,
    enabled boolean not null default true,
    deleted boolean not null default false,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,

    constraint uq_error_types_code unique (code),
    constraint ck_error_types_level check (type_level in (1, 2)),
    constraint ck_error_types_parent check (
        (type_level = 1 and parent_id is null)
        or (type_level = 2 and parent_id is not null)
    ),
    constraint ck_error_types_parent_not_self check (parent_id is null or parent_id <> id),
    constraint ck_error_types_sort_order check (sort_order >= 0)
);

comment on table error_types is '错误类型表';
comment on column error_types.id is '主键ID';
comment on column error_types.parent_id is '父级错误类型ID，对应 error_types.id，由代码维护有效性';
comment on column error_types.type_level is '类型层级：1=一级分类，2=二级分类';
comment on column error_types.code is '错误类型编码，全局唯一';
comment on column error_types.name is '错误类型名称';
comment on column error_types.description is '错误类型说明';
comment on column error_types.sort_order is '排序值，数值越小越靠前';
comment on column error_types.enabled is '是否启用';
comment on column error_types.deleted is '是否逻辑删除';
comment on column error_types.created_at is '创建时间';
comment on column error_types.updated_at is '更新时间';

create index if not exists idx_error_types_parent_id on error_types (parent_id);
create index if not exists idx_error_types_enabled_deleted on error_types (enabled, deleted);



create table if not exists user_error_types (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    error_type_id bigint not null,
    name varchar(128) not null,
    description varchar(255) null,
    status varchar(16) not null default 'ACTIVE',
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,

    constraint ck_user_error_types_name_not_blank check (length(trim(name)) > 0),
    constraint ck_user_error_types_status check (status in ('ACTIVE', 'ARCHIVED'))
);

comment on table user_error_types is '用户错误类型表';
comment on column user_error_types.id is '主键ID';
comment on column user_error_types.user_id is '用户ID，对应 users.id，由代码维护有效性';
comment on column user_error_types.error_type_id is '二级错误类型ID，对应 error_types.id，由代码维护有效性';
comment on column user_error_types.name is '用户定义的错误类型名称';
comment on column user_error_types.description is '用户错误类型说明';
comment on column user_error_types.status is '错误类型状态：ACTIVE=进行中，ARCHIVED=已归档';
comment on column user_error_types.created_at is '创建时间';
comment on column user_error_types.updated_at is '更新时间';

create index if not exists idx_user_error_types_user_status on user_error_types (user_id, status);
create unique index if not exists uq_user_error_types_user_type_name
    on user_error_types (user_id, error_type_id, name)
    where status = 'ACTIVE';

create table if not exists user_answer_errors (
    id bigint generated by default as identity primary key,
    user_answer_id bigint not null,
    user_id bigint not null,
    question_id bigint null,
    error_type_id bigint not null,
    user_error_type_id bigint null,
    original_text text not null,
    issue text not null,
    suggestion text not null,
    severity varchar(16) not null,
    sort_order integer not null default 0,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,

    constraint ck_user_answer_errors_original_text_not_blank check (length(trim(original_text)) > 0),
    constraint ck_user_answer_errors_issue_not_blank check (length(trim(issue)) > 0),
    constraint ck_user_answer_errors_suggestion_not_blank check (length(trim(suggestion)) > 0),
    constraint ck_user_answer_errors_severity check (severity in ('LOW', 'MEDIUM', 'HIGH')),
    constraint ck_user_answer_errors_sort_order check (sort_order >= 0)
);

comment on table user_answer_errors is '用户回答错误记录表';
comment on column user_answer_errors.id is '主键ID';
comment on column user_answer_errors.user_answer_id is '用户回答ID，对应 user_answers.id，由代码维护有效性';
comment on column user_answer_errors.user_id is '用户ID，冗余保存自 user_answers.user_id';
comment on column user_answer_errors.question_id is '题目ID，冗余保存自 user_answers.question_id；纯日语纠错记录为空';
comment on column user_answer_errors.error_type_id is '二级错误类型ID，对应 error_types.id，由代码维护有效性';
comment on column user_answer_errors.user_error_type_id is '用户错误类型ID，对应 user_error_types.id，由代码维护有效性';
comment on column user_answer_errors.original_text is '用户答案中的错误片段';
comment on column user_answer_errors.issue is '错误问题说明';
comment on column user_answer_errors.suggestion is '修改建议';
comment on column user_answer_errors.severity is '错误严重程度：LOW=轻微，MEDIUM=中等，HIGH=严重';
comment on column user_answer_errors.sort_order is '同一次回答中的展示排序';
comment on column user_answer_errors.created_at is '创建时间';
comment on column user_answer_errors.updated_at is '更新时间';

create index if not exists idx_user_answer_errors_user_answer_id on user_answer_errors (user_answer_id);
create index if not exists idx_user_answer_errors_user_error_type_created_at on user_answer_errors (user_id, error_type_id, created_at);
create index if not exists idx_user_answer_errors_user_question on user_answer_errors (user_id, question_id);
create index if not exists idx_user_answer_errors_error_type_id on user_answer_errors (error_type_id);
create index if not exists idx_user_answer_errors_user_error_type_id on user_answer_errors (user_error_type_id);
create index if not exists idx_user_answer_errors_user_error_type_question
    on user_answer_errors (user_error_type_id, question_id);
create index if not exists idx_user_answer_errors_user_created_at
    on user_answer_errors (user_id, created_at);

create table if not exists review_cards (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    user_error_type_id bigint not null,
    status varchar(16) not null default 'ACTIVE',
    ease_factor numeric(5, 4) not null default 2.5000,
    repetition_count integer not null default 0,
    interval_days integer not null default 1,
    lapse_count integer not null default 0,
    due_at timestamp null,
    last_reviewed_at timestamp null,
    mastered_at timestamp null,
    deleted boolean not null default false,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,

    constraint uq_review_cards_user_error_type unique (user_error_type_id),
    constraint ck_review_cards_status check (status in ('ACTIVE', 'MASTERED')),
    constraint ck_review_cards_ease_factor check (ease_factor >= 1.3000),
    constraint ck_review_cards_repetition_count check (repetition_count >= 0),
    constraint ck_review_cards_interval_days check (interval_days >= 1),
    constraint ck_review_cards_lapse_count check (lapse_count >= 0),
    constraint ck_review_cards_status_time check (
        (status = 'ACTIVE' and due_at is not null and mastered_at is null)
        or (status = 'MASTERED' and due_at is null and mastered_at is not null)
    )
);

comment on table review_cards is '用户错误类型复习卡片表';
comment on column review_cards.id is '复习卡片主键ID';
comment on column review_cards.user_id is '卡片所属用户ID，对应 users.id，由代码维护有效性';
comment on column review_cards.user_error_type_id is '用户错误类型ID，对应 user_error_types.id，一种用户错误类型只有一张卡片';
comment on column review_cards.status is '卡片状态：ACTIVE=复习中或等待到期，MASTERED=当前周期已完成并已掌握';
comment on column review_cards.ease_factor is 'SM-2难度因子，默认2.5000，最低1.3000';
comment on column review_cards.repetition_count is '当前连续成功次数，复习失败时归零';
comment on column review_cards.interval_days is '当前SM-2复习间隔天数，失败后重置为1天';
comment on column review_cards.lapse_count is '累计失败次数，包含复习失败和普通练习再次确认同类错误';
comment on column review_cards.due_at is '下次应复习时间，已掌握时为空';
comment on column review_cards.last_reviewed_at is '最近一次影响卡片SM-2状态的时间';
comment on column review_cards.mastered_at is '最近一次完成复习周期并标记掌握的时间，重新激活时清空';
comment on column review_cards.deleted is '逻辑删除标记：false=未删除，true=已删除';
comment on column review_cards.created_at is '创建时间';
comment on column review_cards.updated_at is '更新时间';

create index if not exists idx_review_cards_user_status_due_at
    on review_cards (user_id, deleted, status, due_at);

create table if not exists review_cycles (
    id bigint generated by default as identity primary key,
    review_card_id bigint not null,
    cycle_no integer not null,
    status varchar(16) not null default 'IN_PROGRESS',
    target_success_count integer not null default 4,
    successful_review_count integer not null default 0,
    failed_review_count integer not null default 0,
    verification_required_after timestamp not null default current_timestamp,
    started_at timestamp not null default current_timestamp,
    completed_at timestamp null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,

    constraint uq_review_cycles_card_cycle_no unique (review_card_id, cycle_no),
    constraint ck_review_cycles_cycle_no check (cycle_no >= 1),
    constraint ck_review_cycles_status check (status in ('IN_PROGRESS', 'COMPLETED')),
    constraint ck_review_cycles_target_success_count check (target_success_count = 4),
    constraint ck_review_cycles_successful_review_count check (successful_review_count >= 0),
    constraint ck_review_cycles_failed_review_count check (failed_review_count >= 0),
    constraint ck_review_cycles_status_time check (
        (status = 'IN_PROGRESS' and completed_at is null)
        or (status = 'COMPLETED' and completed_at is not null)
    )
);

comment on table review_cycles is '复习卡片周期表';
comment on column review_cycles.id is '复习周期主键ID';
comment on column review_cycles.review_card_id is '所属复习卡片ID，对应 review_cards.id，由代码维护有效性';
comment on column review_cycles.cycle_no is '卡片周期序号，从1开始递增';
comment on column review_cycles.status is '周期状态：IN_PROGRESS=进行中，COMPLETED=已完成';
comment on column review_cycles.target_success_count is '本周期目标净成功次数，固定为4';
comment on column review_cycles.successful_review_count is '本周期累计成功作答次数，失败时不清零';
comment on column review_cycles.failed_review_count is '本周期累计失败次数，不包含创建新卡片的首次错误';
comment on column review_cycles.verification_required_after is '兼容字段，记录最近新增或再次答错原题的时间';
comment on column review_cycles.started_at is '周期开始时间';
comment on column review_cycles.completed_at is '周期完成时间，进行中时为空';
comment on column review_cycles.created_at is '创建时间';
comment on column review_cycles.updated_at is '更新时间';

create unique index if not exists uq_review_cycles_in_progress_card
    on review_cycles (review_card_id)
    where status = 'IN_PROGRESS';
create index if not exists idx_review_cycles_card_status
    on review_cycles (review_card_id, status);

create table if not exists review_cycle_questions (
    id bigint generated by default as identity primary key,
    review_cycle_id bigint not null,
    question_id bigint not null,
    question_role varchar(16) not null,
    review_status varchar(16) not null default 'PENDING',
    attempt_count integer not null default 0,
    last_quality smallint null,
    last_attempt_at timestamp null,
    passed_at timestamp null,
    sort_order integer not null default 0,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,

    constraint uq_review_cycle_questions_cycle_question unique (review_cycle_id, question_id),
    constraint ck_review_cycle_questions_role check (question_role in ('ORIGINAL', 'DERIVED')),
    constraint ck_review_cycle_questions_status check (review_status in ('PENDING', 'RETRY', 'PASSED')),
    constraint ck_review_cycle_questions_attempt_count check (attempt_count >= 0),
    constraint ck_review_cycle_questions_last_quality check (last_quality is null or last_quality between 0 and 5),
    constraint ck_review_cycle_questions_sort_order check (sort_order >= 0),
    constraint ck_review_cycle_questions_status_time check (
        (review_status = 'PASSED' and passed_at is not null)
        or (review_status in ('PENDING', 'RETRY') and passed_at is null)
    )
);

comment on table review_cycle_questions is '复习周期题目表';
comment on column review_cycle_questions.id is '周期题目主键ID';
comment on column review_cycle_questions.review_cycle_id is '所属复习周期ID，对应 review_cycles.id，由代码维护有效性';
comment on column review_cycle_questions.question_id is '实际题目ID，对应 questions.id，原题和衍生题统一使用题目表';
comment on column review_cycle_questions.question_role is '题目角色：ORIGINAL=错误记录关联原题，DERIVED=AI生成复习衍生题';
comment on column review_cycle_questions.review_status is '复习状态：PENDING=尚未作答，RETRY=失败后等待重试，PASSED=本周期已通过';
comment on column review_cycle_questions.attempt_count is '该题在本周期的总作答次数';
comment on column review_cycle_questions.last_quality is '最近一次SM-2质量分，范围0到5，尚未作答时为空';
comment on column review_cycle_questions.last_attempt_at is '最近作答时间，多个重试题按该时间倒序选择';
comment on column review_cycle_questions.passed_at is '最近一次通过时间，再次失败时清空，历史通过保留在复习事件表';
comment on column review_cycle_questions.sort_order is '同优先级题目的稳定排序值';
comment on column review_cycle_questions.created_at is '加入本周期的时间';
comment on column review_cycle_questions.updated_at is '更新时间';

create unique index if not exists uq_review_cycle_questions_derived_owner
    on review_cycle_questions (question_id)
    where question_role = 'DERIVED';
create unique index if not exists uq_review_cycle_questions_active_derived
    on review_cycle_questions (review_cycle_id)
    where question_role = 'DERIVED' and review_status in ('PENDING', 'RETRY');
create index if not exists idx_review_cycle_questions_cycle_status_attempt
    on review_cycle_questions (review_cycle_id, review_status, last_attempt_at desc);
create index if not exists idx_review_cycle_questions_question_id
    on review_cycle_questions (question_id);

create table if not exists review_attempts (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    review_card_id bigint not null,
    review_cycle_id bigint not null,
    review_cycle_question_id bigint not null,
    user_answer_id bigint not null,
    attempt_source varchar(24) not null,
    result varchar(16) not null,
    sm2_quality smallint not null,
    target_error_resolved boolean not null,
    ai_feedback text null,
    ease_factor_after numeric(5, 4) not null,
    repetition_count_after integer not null,
    interval_days_after integer not null,
    cycle_success_count_after integer not null,
    next_due_at timestamp null,
    created_at timestamp not null default current_timestamp,

    constraint uq_review_attempts_card_user_answer unique (review_card_id, user_answer_id),
    constraint ck_review_attempts_source check (attempt_source in ('REVIEW', 'PRACTICE_ERROR')),
    constraint ck_review_attempts_result check (result in ('PASS', 'FAIL')),
    constraint ck_review_attempts_quality check (sm2_quality between 0 and 5),
    constraint ck_review_attempts_result_quality check (
        (result = 'PASS' and sm2_quality between 3 and 5 and target_error_resolved = true)
        or (result = 'FAIL' and sm2_quality between 0 and 2 and target_error_resolved = false)
    ),
    constraint ck_review_attempts_practice_error check (
        attempt_source <> 'PRACTICE_ERROR'
        or (result = 'FAIL' and sm2_quality = 2 and target_error_resolved = false)
    ),
    constraint ck_review_attempts_ease_factor check (ease_factor_after >= 1.3000),
    constraint ck_review_attempts_repetition_count check (repetition_count_after >= 0),
    constraint ck_review_attempts_interval_days check (interval_days_after >= 1),
    constraint ck_review_attempts_cycle_success_count check (cycle_success_count_after >= 0),
    constraint ck_review_attempts_fail_due_at check (result <> 'FAIL' or next_due_at is not null)
);

comment on table review_attempts is '复习作答事件表';
comment on column review_attempts.id is '复习事件主键ID';
comment on column review_attempts.user_id is '作答用户ID，对应 users.id，冗余保存用于用户维度统计';
comment on column review_attempts.review_card_id is '本次事件影响的复习卡片ID，对应 review_cards.id';
comment on column review_attempts.review_cycle_id is '本次事件所属复习周期ID，对应 review_cycles.id';
comment on column review_attempts.review_cycle_question_id is '本次事件对应周期题目ID，对应 review_cycle_questions.id';
comment on column review_attempts.user_answer_id is '实际用户答案ID，对应 user_answers.id';
comment on column review_attempts.attempt_source is '事件来源：REVIEW=复习作答，PRACTICE_ERROR=普通练习确认同类错误';
comment on column review_attempts.result is '复习结果：PASS=通过，FAIL=失败';
comment on column review_attempts.sm2_quality is 'SM-2质量分，范围0到5，普通练习确认同类错误固定为2';
comment on column review_attempts.target_error_resolved is '本次回答是否解决卡片针对的目标错误';
comment on column review_attempts.ai_feedback is '复习专用AI评分反馈，普通练习失败事件可以为空';
comment on column review_attempts.ease_factor_after is '处理本次事件后的SM-2难度因子';
comment on column review_attempts.repetition_count_after is '处理本次事件后的连续成功次数';
comment on column review_attempts.interval_days_after is '处理本次事件后的复习间隔天数';
comment on column review_attempts.cycle_success_count_after is '处理本次事件后的周期累计成功次数';
comment on column review_attempts.next_due_at is '本次事件计算出的下次复习时间，完成周期时为空';
comment on column review_attempts.created_at is '事件发生时间，事件记录创建后不再更新';

create index if not exists idx_review_attempts_card_created_at
    on review_attempts (review_card_id, created_at);
create index if not exists idx_review_attempts_user_answer_id
    on review_attempts (user_answer_id);
create index if not exists idx_review_attempts_user_created_at
    on review_attempts (user_id, created_at);
