create table if not exists tags (
    id bigint generated by default as identity primary key,
    tag_type varchar(32) not null,
    parent_id bigint null,
    code varchar(64) not null,
    name varchar(64) not null,
    description varchar(255) null,
    sort_order integer not null default 0,
    enabled boolean not null default true,
    deleted boolean not null default false,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,

    constraint uq_tags_code unique (code),
    constraint ck_tags_type check (tag_type in ('SCENE', 'FUNCTION', 'GENRE')),
    constraint ck_tags_parent_not_self check (parent_id is null or parent_id <> id)
);

comment on table tags is '标签表';
comment on column tags.id is '主键ID';
alter table tags drop constraint if exists ck_tags_type;
alter table tags
    add constraint ck_tags_type
    check (tag_type in ('SCENE', 'FUNCTION', 'GENRE'));

comment on column tags.tag_type is '标签类型：SCENE=场景标签，FUNCTION=功能标签，GENRE=文章体裁标签';
comment on column tags.parent_id is '父标签ID，用于一级、二级标签层级关系，由代码维护有效性';
comment on column tags.code is '标签编码，供后端和AI稳定识别使用';
comment on column tags.name is '标签中文名称';
comment on column tags.description is '标签说明';
comment on column tags.sort_order is '排序值，数值越小越靠前';
comment on column tags.enabled is '是否启用';
comment on column tags.deleted is '是否删除';
comment on column tags.created_at is '创建时间';
comment on column tags.updated_at is '更新时间';

create index if not exists idx_tags_type on tags (tag_type);
create index if not exists idx_tags_parent_id on tags (parent_id);
create index if not exists idx_tags_enabled_deleted on tags (enabled, deleted);

create table if not exists question_tags (
    id bigint generated by default as identity primary key,
    question_id bigint not null,
    tag_id bigint not null,
    created_at timestamp not null default current_timestamp,

    constraint uq_question_tags_question_id_tag_id unique (question_id, tag_id)
);

comment on table question_tags is '题目标签关联表';
comment on column question_tags.id is '主键ID';
comment on column question_tags.question_id is '题目ID，对应 questions.id，由代码维护有效性';
comment on column question_tags.tag_id is '标签ID，对应 tags.id，由代码维护有效性';
comment on column question_tags.created_at is '创建时间';

create index if not exists idx_question_tags_question_id on question_tags (question_id);
create index if not exists idx_question_tags_tag_id on question_tags (tag_id);

-- 初始化固定标签数据
drop table if exists seed_tags;

create temporary table seed_tags (
    tag_type varchar(32) not null,
    parent_code varchar(64) null,
    code varchar(64) not null,
    name varchar(64) not null,
    description varchar(255) null,
    sort_order integer not null
);

insert into seed_tags (tag_type, parent_code, code, name, description, sort_order) values
('SCENE', null, 'DAILY_LIFE', '日常生活', '场景一级标签', 1000),
('SCENE', 'DAILY_LIFE', 'DAILY_LIFE_HOME', '居家', '日常生活场景标签', 1010),
('SCENE', 'DAILY_LIFE', 'DAILY_LIFE_DAILY_TASKS', '日常事务', '日常生活场景标签', 1020),
('SCENE', 'DAILY_LIFE', 'DAILY_LIFE_NEIGHBORHOOD', '邻里', '日常生活场景标签', 1030),
('SCENE', 'DAILY_LIFE', 'DAILY_LIFE_WEATHER', '天气', '日常生活场景标签', 1040),
('SCENE', 'DAILY_LIFE', 'DAILY_LIFE_DATE_TIME', '时间日期', '日常生活场景标签', 1050),
('SCENE', 'DAILY_LIFE', 'DAILY_LIFE_PERSONAL_SCHEDULE', '个人安排', '日常生活场景标签', 1060),
('SCENE', null, 'SOCIAL', '社交交流', '场景一级标签', 2000),
('SCENE', 'SOCIAL', 'SOCIAL_FRIENDS', '朋友交流', '社交交流场景标签', 2010),
('SCENE', 'SOCIAL', 'SOCIAL_ACQUAINTANCES', '熟人交流', '社交交流场景标签', 2020),
('SCENE', 'SOCIAL', 'SOCIAL_FIRST_MEETING', '初次见面', '社交交流场景标签', 2030),
('SCENE', 'SOCIAL', 'SOCIAL_GATHERING', '聚会', '社交交流场景标签', 2040),
('SCENE', 'SOCIAL', 'SOCIAL_VISIT', '拜访', '社交交流场景标签', 2050),
('SCENE', 'SOCIAL', 'SOCIAL_ONLINE', '线上交流', '社交交流场景标签', 2060),
('SCENE', null, 'EDUCATION', '学校学习', '场景一级标签', 3000),
('SCENE', 'EDUCATION', 'EDUCATION_CLASSROOM', '课堂', '学校学习场景标签', 3010),
('SCENE', 'EDUCATION', 'EDUCATION_TEACHER_STUDENT', '师生交流', '学校学习场景标签', 3020),
('SCENE', 'EDUCATION', 'EDUCATION_CLASSMATES', '同学交流', '学校学习场景标签', 3030),
('SCENE', 'EDUCATION', 'EDUCATION_EXAM', '考试', '学校学习场景标签', 3040),
('SCENE', 'EDUCATION', 'EDUCATION_HOMEWORK', '作业', '学校学习场景标签', 3050),
('SCENE', 'EDUCATION', 'EDUCATION_SELF_STUDY', '自习', '学校学习场景标签', 3060),
('SCENE', 'EDUCATION', 'EDUCATION_SCHOOL_AFFAIRS', '学校事务', '学校学习场景标签', 3070),
('SCENE', null, 'WORK', '工作职场', '场景一级标签', 4000),
('SCENE', 'WORK', 'WORK_COLLEAGUES', '同事交流', '工作职场场景标签', 4010),
('SCENE', 'WORK', 'WORK_SUPERVISOR_SUBORDINATE', '上下级交流', '工作职场场景标签', 4020),
('SCENE', 'WORK', 'WORK_MEETING', '会议', '工作职场场景标签', 4030),
('SCENE', 'WORK', 'WORK_REPORT', '工作汇报', '工作职场场景标签', 4040),
('SCENE', 'WORK', 'WORK_TASK_COMMUNICATION', '任务沟通', '工作职场场景标签', 4050),
('SCENE', 'WORK', 'WORK_SOCIALIZING', '职场社交', '工作职场场景标签', 4060),
('SCENE', 'WORK', 'WORK_JOB_INTERVIEW', '求职面试', '工作职场场景标签', 4070),
('SCENE', null, 'PART_TIME_JOB', '兼职', '场景一级标签', 5000),
('SCENE', 'PART_TIME_JOB', 'PART_TIME_JOB_SHIFT', '排班', '兼职场景标签', 5010),
('SCENE', 'PART_TIME_JOB', 'PART_TIME_JOB_LEAVE_REQUEST', '请假', '兼职场景标签', 5020),
('SCENE', 'PART_TIME_JOB', 'PART_TIME_JOB_WORK_CONFIRMATION', '工作确认', '兼职场景标签', 5030),
('SCENE', 'PART_TIME_JOB', 'PART_TIME_JOB_MANAGER_COMMUNICATION', '店长沟通', '兼职场景标签', 5040),
('SCENE', 'PART_TIME_JOB', 'PART_TIME_JOB_COWORKER_COOPERATION', '同事协作', '兼职场景标签', 5050),
('SCENE', 'PART_TIME_JOB', 'PART_TIME_JOB_CUSTOMER_SERVICE', '顾客接待', '兼职场景标签', 5060),
('SCENE', null, 'SHOPPING', '购物消费', '场景一级标签', 6000),
('SCENE', 'SHOPPING', 'SHOPPING_PRODUCT_INQUIRY', '商品询问', '购物消费场景标签', 6010),
('SCENE', 'SHOPPING', 'SHOPPING_PRODUCT_SELECTION', '商品选择', '购物消费场景标签', 6020),
('SCENE', 'SHOPPING', 'SHOPPING_TRY_ON', '试用试穿', '购物消费场景标签', 6030),
('SCENE', 'SHOPPING', 'SHOPPING_CHECKOUT', '结账', '购物消费场景标签', 6040),
('SCENE', 'SHOPPING', 'SHOPPING_RETURN_EXCHANGE', '退换货', '购物消费场景标签', 6050),
('SCENE', 'SHOPPING', 'SHOPPING_AFTER_SALES', '售后服务', '购物消费场景标签', 6060),
('SCENE', null, 'DINING', '餐饮', '场景一级标签', 7000),
('SCENE', 'DINING', 'DINING_ENTERING', '入店', '餐饮场景标签', 7010),
('SCENE', 'DINING', 'DINING_ORDERING', '点餐', '餐饮场景标签', 7020),
('SCENE', 'DINING', 'DINING_EATING', '用餐', '餐饮场景标签', 7030),
('SCENE', 'DINING', 'DINING_ADDITIONAL_ORDER', '追加点单', '餐饮场景标签', 7040),
('SCENE', 'DINING', 'DINING_CHECKOUT', '结账', '餐饮场景标签', 7050),
('SCENE', 'DINING', 'DINING_RESERVATION', '预约', '餐饮场景标签', 7060),
('SCENE', 'DINING', 'DINING_TAKEOUT_DELIVERY', '外卖', '餐饮场景标签', 7070),
('SCENE', null, 'TRANSPORT', '交通出行', '场景一级标签', 8000),
('SCENE', 'TRANSPORT', 'TRANSPORT_DIRECTIONS', '问路', '交通出行场景标签', 8010),
('SCENE', 'TRANSPORT', 'TRANSPORT_WALKING', '步行', '交通出行场景标签', 8020),
('SCENE', 'TRANSPORT', 'TRANSPORT_BUS', '公交', '交通出行场景标签', 8030),
('SCENE', 'TRANSPORT', 'TRANSPORT_TRAIN', '电车', '交通出行场景标签', 8040),
('SCENE', 'TRANSPORT', 'TRANSPORT_SUBWAY', '地铁', '交通出行场景标签', 8050),
('SCENE', 'TRANSPORT', 'TRANSPORT_SHINKANSEN', '新干线', '交通出行场景标签', 8060),
('SCENE', 'TRANSPORT', 'TRANSPORT_TAXI', '出租车', '交通出行场景标签', 8070),
('SCENE', 'TRANSPORT', 'TRANSPORT_DRIVING', '驾车', '交通出行场景标签', 8080),
('SCENE', 'TRANSPORT', 'TRANSPORT_STATION_AIRPORT', '车站机场', '交通出行场景标签', 8090),
('SCENE', null, 'TRAVEL', '旅行住宿', '场景一级标签', 9000),
('SCENE', 'TRAVEL', 'TRAVEL_ITINERARY', '行程安排', '旅行住宿场景标签', 9010),
('SCENE', 'TRAVEL', 'TRAVEL_SIGHTSEEING', '观光', '旅行住宿场景标签', 9020),
('SCENE', 'TRAVEL', 'TRAVEL_HOTEL_CHECKIN', '酒店入住', '旅行住宿场景标签', 9030),
('SCENE', 'TRAVEL', 'TRAVEL_HOTEL_SERVICE', '酒店服务', '旅行住宿场景标签', 9040),
('SCENE', 'TRAVEL', 'TRAVEL_CHECKOUT', '退房', '旅行住宿场景标签', 9050),
('SCENE', 'TRAVEL', 'TRAVEL_LUGGAGE', '行李', '旅行住宿场景标签', 9060),
('SCENE', null, 'HEALTHCARE', '医疗健康', '场景一级标签', 10000),
('SCENE', 'HEALTHCARE', 'HEALTHCARE_REGISTRATION', '挂号', '医疗健康场景标签', 10010),
('SCENE', 'HEALTHCARE', 'HEALTHCARE_SYMPTOMS', '描述症状', '医疗健康场景标签', 10020),
('SCENE', 'HEALTHCARE', 'HEALTHCARE_CONSULTATION', '问诊', '医疗健康场景标签', 10030),
('SCENE', 'HEALTHCARE', 'HEALTHCARE_EXAMINATION', '检查', '医疗健康场景标签', 10040),
('SCENE', 'HEALTHCARE', 'HEALTHCARE_PHARMACY', '药店', '医疗健康场景标签', 10050),
('SCENE', 'HEALTHCARE', 'HEALTHCARE_PHYSICAL_CONDITION', '身体状态', '医疗健康场景标签', 10060),
('SCENE', null, 'PUBLIC_SERVICE', '公共服务', '场景一级标签', 11000),
('SCENE', 'PUBLIC_SERVICE', 'PUBLIC_SERVICE_GOVERNMENT_OFFICE', '政府机关', '公共服务场景标签', 11010),
('SCENE', 'PUBLIC_SERVICE', 'PUBLIC_SERVICE_PROCEDURES', '手续办理', '公共服务场景标签', 11020),
('SCENE', 'PUBLIC_SERVICE', 'PUBLIC_SERVICE_DOCUMENTS', '证件', '公共服务场景标签', 11030),
('SCENE', 'PUBLIC_SERVICE', 'PUBLIC_SERVICE_POST_OFFICE', '邮局', '公共服务场景标签', 11040),
('SCENE', 'PUBLIC_SERVICE', 'PUBLIC_SERVICE_POLICE', '警察', '公共服务场景标签', 11050),
('SCENE', 'PUBLIC_SERVICE', 'PUBLIC_SERVICE_FACILITIES', '公共设施', '公共服务场景标签', 11060),
('SCENE', null, 'FINANCE', '金融', '场景一级标签', 12000),
('SCENE', 'FINANCE', 'FINANCE_BANK', '银行', '金融场景标签', 12010),
('SCENE', 'FINANCE', 'FINANCE_ACCOUNT_OPENING', '开户', '金融场景标签', 12020),
('SCENE', 'FINANCE', 'FINANCE_TRANSFER', '转账', '金融场景标签', 12030),
('SCENE', 'FINANCE', 'FINANCE_WITHDRAWAL', '取款', '金融场景标签', 12040),
('SCENE', 'FINANCE', 'FINANCE_PAYMENT', '支付', '金融场景标签', 12050),
('SCENE', 'FINANCE', 'FINANCE_BILL', '账单', '金融场景标签', 12060),
('SCENE', 'FINANCE', 'FINANCE_INSURANCE', '保险', '金融场景标签', 12070),
('SCENE', null, 'HOUSING', '居住', '场景一级标签', 13000),
('SCENE', 'HOUSING', 'HOUSING_SEARCH', '找房', '居住场景标签', 13010),
('SCENE', 'HOUSING', 'HOUSING_VIEWING', '看房', '居住场景标签', 13020),
('SCENE', 'HOUSING', 'HOUSING_CONTRACT', '签约', '居住场景标签', 13030),
('SCENE', 'HOUSING', 'HOUSING_RENT', '房租', '居住场景标签', 13040),
('SCENE', 'HOUSING', 'HOUSING_PROPERTY_MANAGEMENT', '物业', '居住场景标签', 13050),
('SCENE', 'HOUSING', 'HOUSING_REPAIR', '维修', '居住场景标签', 13060),
('SCENE', 'HOUSING', 'HOUSING_MOVING', '搬家', '居住场景标签', 13070),
('SCENE', null, 'COMMUNICATION', '通信网络', '场景一级标签', 14000),
('SCENE', 'COMMUNICATION', 'COMMUNICATION_PHONE', '电话', '通信网络场景标签', 14010),
('SCENE', 'COMMUNICATION', 'COMMUNICATION_TEXT_MESSAGE', '短信', '通信网络场景标签', 14020),
('SCENE', 'COMMUNICATION', 'COMMUNICATION_EMAIL', '邮件', '通信网络场景标签', 14030),
('SCENE', 'COMMUNICATION', 'COMMUNICATION_NETWORK', '网络', '通信网络场景标签', 14040),
('SCENE', 'COMMUNICATION', 'COMMUNICATION_MOBILE_PHONE', '手机', '通信网络场景标签', 14050),
('SCENE', 'COMMUNICATION', 'COMMUNICATION_DELIVERY_LOGISTICS', '快递物流', '通信网络场景标签', 14060),
('SCENE', null, 'LEISURE', '娱乐休闲', '场景一级标签', 15000),
('SCENE', 'LEISURE', 'LEISURE_HOBBIES', '兴趣爱好', '娱乐休闲场景标签', 15010),
('SCENE', 'LEISURE', 'LEISURE_GAMES', '游戏', '娱乐休闲场景标签', 15020),
('SCENE', 'LEISURE', 'LEISURE_ANIME_FILM', '动漫影视', '娱乐休闲场景标签', 15030),
('SCENE', 'LEISURE', 'LEISURE_MUSIC', '音乐', '娱乐休闲场景标签', 15040),
('SCENE', 'LEISURE', 'LEISURE_SPORTS', '运动', '娱乐休闲场景标签', 15050),
('SCENE', 'LEISURE', 'LEISURE_ACTIVITIES', '活动', '娱乐休闲场景标签', 15060),
('SCENE', null, 'RELATIONSHIP', '人际关系', '场景一级标签', 16000),
('SCENE', 'RELATIONSHIP', 'RELATIONSHIP_FAMILY', '家庭', '人际关系场景标签', 16010),
('SCENE', 'RELATIONSHIP', 'RELATIONSHIP_FRIENDS', '朋友', '人际关系场景标签', 16020),
('SCENE', 'RELATIONSHIP', 'RELATIONSHIP_ROMANCE', '恋爱', '人际关系场景标签', 16030),
('SCENE', 'RELATIONSHIP', 'RELATIONSHIP_COLLEAGUES', '同事', '人际关系场景标签', 16040),
('SCENE', 'RELATIONSHIP', 'RELATIONSHIP_SENIOR_JUNIOR', '前后辈', '人际关系场景标签', 16050),
('SCENE', 'RELATIONSHIP', 'RELATIONSHIP_CONFLICT', '人际矛盾', '人际关系场景标签', 16060),
('SCENE', null, 'BUSINESS', '商务正式', '场景一级标签', 17000),
('SCENE', 'BUSINESS', 'BUSINESS_CLIENT_COMMUNICATION', '客户交流', '商务正式场景标签', 17010),
('SCENE', 'BUSINESS', 'BUSINESS_MEETING', '商务会议', '商务正式场景标签', 17020),
('SCENE', 'BUSINESS', 'BUSINESS_EMAIL', '商务邮件', '商务正式场景标签', 17030),
('SCENE', 'BUSINESS', 'BUSINESS_RECEPTION', '接待', '商务正式场景标签', 17040),
('SCENE', 'BUSINESS', 'BUSINESS_APPOINTMENT', '预约', '商务正式场景标签', 17050),
('SCENE', 'BUSINESS', 'BUSINESS_NEGOTIATION', '谈判', '商务正式场景标签', 17060),
('SCENE', 'BUSINESS', 'BUSINESS_COOPERATION', '合作', '商务正式场景标签', 17070),
('SCENE', null, 'EMERGENCY', '紧急情况', '场景一级标签', 18000),
('SCENE', 'EMERGENCY', 'EMERGENCY_HELP_REQUEST', '求助', '紧急情况场景标签', 18010),
('SCENE', 'EMERGENCY', 'EMERGENCY_REPORT_POLICE', '报警', '紧急情况场景标签', 18020),
('SCENE', 'EMERGENCY', 'EMERGENCY_LOST_ITEM', '失物', '紧急情况场景标签', 18030),
('SCENE', 'EMERGENCY', 'EMERGENCY_ACCIDENT', '事故', '紧急情况场景标签', 18040),
('SCENE', 'EMERGENCY', 'EMERGENCY_FEELING_UNWELL', '身体不适', '紧急情况场景标签', 18050),
('SCENE', 'EMERGENCY', 'EMERGENCY_DISASTER', '灾害', '紧急情况场景标签', 18060),
('SCENE', null, 'GENERAL', '泛用对话', '场景一级标签', 19000),
('SCENE', 'GENERAL', 'GENERAL_NO_SPECIFIC_SCENE', '无明确场景', '泛用对话场景标签', 19010),
('SCENE', 'GENERAL', 'GENERAL_CONVERSATION', '一般交流', '泛用对话场景标签', 19020),
('FUNCTION', null, 'FUNCTION_INFO_EXCHANGE', '信息交流', '功能一级标签', 20000),
('FUNCTION', 'FUNCTION_INFO_EXCHANGE', 'FUNCTION_STATE_FACT', '陈述事实', '信息交流功能标签', 20010),
('FUNCTION', 'FUNCTION_INFO_EXCHANGE', 'FUNCTION_PROVIDE_INFO', '提供信息', '信息交流功能标签', 20020),
('FUNCTION', 'FUNCTION_INFO_EXCHANGE', 'FUNCTION_ASK_INFO', '询问信息', '信息交流功能标签', 20030),
('FUNCTION', 'FUNCTION_INFO_EXCHANGE', 'FUNCTION_ANSWER_QUESTION', '回答问题', '信息交流功能标签', 20040),
('FUNCTION', 'FUNCTION_INFO_EXCHANGE', 'FUNCTION_CONFIRM_INFO', '确认信息', '信息交流功能标签', 20050),
('FUNCTION', 'FUNCTION_INFO_EXCHANGE', 'FUNCTION_ADD_INFO', '补充信息', '信息交流功能标签', 20060),
('FUNCTION', 'FUNCTION_INFO_EXCHANGE', 'FUNCTION_CORRECT_INFO', '纠正信息', '信息交流功能标签', 20070),
('FUNCTION', null, 'FUNCTION_DESCRIPTION', '描述', '功能一级标签', 21000),
('FUNCTION', 'FUNCTION_DESCRIPTION', 'FUNCTION_DESCRIBE_PERSON', '描述人物', '描述功能标签', 21010),
('FUNCTION', 'FUNCTION_DESCRIPTION', 'FUNCTION_DESCRIBE_OBJECT', '描述事物', '描述功能标签', 21020),
('FUNCTION', 'FUNCTION_DESCRIPTION', 'FUNCTION_DESCRIBE_STATE', '描述状态', '描述功能标签', 21030),
('FUNCTION', 'FUNCTION_DESCRIPTION', 'FUNCTION_DESCRIBE_CHANGE', '描述变化', '描述功能标签', 21040),
('FUNCTION', 'FUNCTION_DESCRIPTION', 'FUNCTION_DESCRIBE_EXPERIENCE', '描述经历', '描述功能标签', 21050),
('FUNCTION', 'FUNCTION_DESCRIPTION', 'FUNCTION_DESCRIBE_PROCESS', '描述过程', '描述功能标签', 21060),
('FUNCTION', null, 'FUNCTION_OPINION', '意见', '功能一级标签', 22000),
('FUNCTION', 'FUNCTION_OPINION', 'FUNCTION_EXPRESS_OPINION', '表达意见', '意见功能标签', 22010),
('FUNCTION', 'FUNCTION_OPINION', 'FUNCTION_ASK_OPINION', '询问意见', '意见功能标签', 22020),
('FUNCTION', 'FUNCTION_OPINION', 'FUNCTION_AGREE', '赞同', '意见功能标签', 22030),
('FUNCTION', 'FUNCTION_OPINION', 'FUNCTION_PARTLY_AGREE', '部分赞同', '意见功能标签', 22040),
('FUNCTION', 'FUNCTION_OPINION', 'FUNCTION_DISAGREE', '反对', '意见功能标签', 22050),
('FUNCTION', 'FUNCTION_OPINION', 'FUNCTION_RESERVE_OPINION', '保留意见', '意见功能标签', 22060),
('FUNCTION', null, 'FUNCTION_JUDGMENT', '判断', '功能一级标签', 23000),
('FUNCTION', 'FUNCTION_JUDGMENT', 'FUNCTION_EXPRESS_JUDGMENT', '表达判断', '判断功能标签', 23010),
('FUNCTION', 'FUNCTION_JUDGMENT', 'FUNCTION_INFER', '推测', '判断功能标签', 23020),
('FUNCTION', 'FUNCTION_JUDGMENT', 'FUNCTION_POSSIBILITY', '可能性', '判断功能标签', 23030),
('FUNCTION', 'FUNCTION_JUDGMENT', 'FUNCTION_UNCERTAINTY', '不确定', '判断功能标签', 23040),
('FUNCTION', 'FUNCTION_JUDGMENT', 'FUNCTION_COMPARE', '比较', '判断功能标签', 23050),
('FUNCTION', 'FUNCTION_JUDGMENT', 'FUNCTION_EVALUATE', '评价', '判断功能标签', 23060),
('FUNCTION', null, 'FUNCTION_EMOTION', '感情', '功能一级标签', 24000),
('FUNCTION', 'FUNCTION_EMOTION', 'FUNCTION_EXPRESS_HAPPINESS', '表达开心', '感情功能标签', 24010),
('FUNCTION', 'FUNCTION_EMOTION', 'FUNCTION_EXPRESS_SATISFACTION', '满意', '感情功能标签', 24020),
('FUNCTION', 'FUNCTION_EMOTION', 'FUNCTION_EXPRESS_LIKE', '喜欢', '感情功能标签', 24030),
('FUNCTION', 'FUNCTION_EMOTION', 'FUNCTION_EXPRESS_DISLIKE', '不喜欢', '感情功能标签', 24040),
('FUNCTION', 'FUNCTION_EMOTION', 'FUNCTION_EXPRESS_DISSATISFACTION', '不满', '感情功能标签', 24050),
('FUNCTION', 'FUNCTION_EMOTION', 'FUNCTION_EXPRESS_DISAPPOINTMENT', '失望', '感情功能标签', 24060),
('FUNCTION', 'FUNCTION_EMOTION', 'FUNCTION_EXPRESS_SURPRISE', '惊讶', '感情功能标签', 24070),
('FUNCTION', 'FUNCTION_EMOTION', 'FUNCTION_EXPRESS_WORRY', '担心', '感情功能标签', 24080),
('FUNCTION', 'FUNCTION_EMOTION', 'FUNCTION_EXPRESS_FEAR', '害怕', '感情功能标签', 24090),
('FUNCTION', 'FUNCTION_EMOTION', 'FUNCTION_EXPRESS_REGRET', '遗憾', '感情功能标签', 24100),
('FUNCTION', 'FUNCTION_EMOTION', 'FUNCTION_EXPRESS_CONFUSION', '困惑', '感情功能标签', 24110),
('FUNCTION', null, 'FUNCTION_INTENTION', '意愿', '功能一级标签', 25000),
('FUNCTION', 'FUNCTION_INTENTION', 'FUNCTION_EXPRESS_INTENTION', '表达意愿', '意愿功能标签', 25010),
('FUNCTION', 'FUNCTION_INTENTION', 'FUNCTION_EXPRESS_HOPE', '表达希望', '意愿功能标签', 25020),
('FUNCTION', 'FUNCTION_INTENTION', 'FUNCTION_EXPRESS_PLAN', '表达计划', '意愿功能标签', 25030),
('FUNCTION', 'FUNCTION_INTENTION', 'FUNCTION_EXPRESS_DECISION', '表达决定', '意愿功能标签', 25040),
('FUNCTION', 'FUNCTION_INTENTION', 'FUNCTION_REFUSE_INTENTION', '拒绝意愿', '意愿功能标签', 25050),
('FUNCTION', 'FUNCTION_INTENTION', 'FUNCTION_CHANGE_DECISION', '改变决定', '意愿功能标签', 25060),
('FUNCTION', null, 'FUNCTION_REQUEST', '请求', '功能一级标签', 26000),
('FUNCTION', 'FUNCTION_REQUEST', 'FUNCTION_MAKE_REQUEST', '提出请求', '请求功能标签', 26010),
('FUNCTION', 'FUNCTION_REQUEST', 'FUNCTION_REQUEST_HELP', '请求帮助', '请求功能标签', 26020),
('FUNCTION', 'FUNCTION_REQUEST', 'FUNCTION_REQUEST_CONFIRMATION', '请求确认', '请求功能标签', 26030),
('FUNCTION', 'FUNCTION_REQUEST', 'FUNCTION_REQUEST_EXPLANATION', '请求说明', '请求功能标签', 26040),
('FUNCTION', null, 'FUNCTION_INSTRUCTION', '指示', '功能一级标签', 27000),
('FUNCTION', 'FUNCTION_INSTRUCTION', 'FUNCTION_INSTRUCT', '指示', '指示功能标签', 27010),
('FUNCTION', 'FUNCTION_INSTRUCTION', 'FUNCTION_COMMAND', '命令', '指示功能标签', 27020),
('FUNCTION', 'FUNCTION_INSTRUCTION', 'FUNCTION_PROHIBIT', '禁止', '指示功能标签', 27030),
('FUNCTION', 'FUNCTION_INSTRUCTION', 'FUNCTION_REMIND', '提醒', '指示功能标签', 27040),
('FUNCTION', 'FUNCTION_INSTRUCTION', 'FUNCTION_WARN', '警告', '指示功能标签', 27050),
('FUNCTION', 'FUNCTION_INSTRUCTION', 'FUNCTION_URGE', '催促', '指示功能标签', 27060),
('FUNCTION', null, 'FUNCTION_SUGGESTION', '建议', '功能一级标签', 28000),
('FUNCTION', 'FUNCTION_SUGGESTION', 'FUNCTION_MAKE_SUGGESTION', '提出建议', '建议功能标签', 28010),
('FUNCTION', 'FUNCTION_SUGGESTION', 'FUNCTION_ASK_SUGGESTION', '征求建议', '建议功能标签', 28020),
('FUNCTION', 'FUNCTION_SUGGESTION', 'FUNCTION_RECOMMEND', '推荐', '建议功能标签', 28030),
('FUNCTION', 'FUNCTION_SUGGESTION', 'FUNCTION_ADVISE', '劝告', '建议功能标签', 28040),
('FUNCTION', 'FUNCTION_SUGGESTION', 'FUNCTION_PROPOSE_PLAN', '提出方案', '建议功能标签', 28050),
('FUNCTION', null, 'FUNCTION_INVITATION', '邀请', '功能一级标签', 29000),
('FUNCTION', 'FUNCTION_INVITATION', 'FUNCTION_INVITE', '邀请', '邀请功能标签', 29010),
('FUNCTION', 'FUNCTION_INVITATION', 'FUNCTION_ACCEPT_INVITATION', '接受邀请', '邀请功能标签', 29020),
('FUNCTION', 'FUNCTION_INVITATION', 'FUNCTION_DECLINE_INVITATION', '拒绝邀请', '邀请功能标签', 29030),
('FUNCTION', 'FUNCTION_INVITATION', 'FUNCTION_MAKE_APPOINTMENT', '约定', '邀请功能标签', 29040),
('FUNCTION', 'FUNCTION_INVITATION', 'FUNCTION_ADJUST_APPOINTMENT', '调整约定', '邀请功能标签', 29050),
('FUNCTION', 'FUNCTION_INVITATION', 'FUNCTION_CANCEL_APPOINTMENT', '取消约定', '邀请功能标签', 29060),
('FUNCTION', null, 'FUNCTION_PERMISSION', '许可', '功能一级标签', 30000),
('FUNCTION', 'FUNCTION_PERMISSION', 'FUNCTION_ASK_PERMISSION', '询问许可', '许可功能标签', 30010),
('FUNCTION', 'FUNCTION_PERMISSION', 'FUNCTION_GRANT_PERMISSION', '给予许可', '许可功能标签', 30020),
('FUNCTION', 'FUNCTION_PERMISSION', 'FUNCTION_REFUSE_PERMISSION', '拒绝许可', '许可功能标签', 30030),
('FUNCTION', null, 'FUNCTION_SOCIAL_ETIQUETTE', '社交礼仪', '功能一级标签', 31000),
('FUNCTION', 'FUNCTION_SOCIAL_ETIQUETTE', 'FUNCTION_GREETING', '问候', '社交礼仪功能标签', 31010),
('FUNCTION', 'FUNCTION_SOCIAL_ETIQUETTE', 'FUNCTION_FAREWELL', '告别', '社交礼仪功能标签', 31020),
('FUNCTION', 'FUNCTION_SOCIAL_ETIQUETTE', 'FUNCTION_THANK', '感谢', '社交礼仪功能标签', 31030),
('FUNCTION', 'FUNCTION_SOCIAL_ETIQUETTE', 'FUNCTION_RESPOND_THANKS', '回应感谢', '社交礼仪功能标签', 31040),
('FUNCTION', 'FUNCTION_SOCIAL_ETIQUETTE', 'FUNCTION_APOLOGIZE', '道歉', '社交礼仪功能标签', 31050),
('FUNCTION', 'FUNCTION_SOCIAL_ETIQUETTE', 'FUNCTION_RESPOND_APOLOGY', '回应道歉', '社交礼仪功能标签', 31060),
('FUNCTION', 'FUNCTION_SOCIAL_ETIQUETTE', 'FUNCTION_CONGRATULATE', '祝贺', '社交礼仪功能标签', 31070),
('FUNCTION', 'FUNCTION_SOCIAL_ETIQUETTE', 'FUNCTION_BLESSING', '祝福', '社交礼仪功能标签', 31080),
('FUNCTION', null, 'FUNCTION_INTRODUCTION', '介绍', '功能一级标签', 32000),
('FUNCTION', 'FUNCTION_INTRODUCTION', 'FUNCTION_SELF_INTRODUCTION', '自我介绍', '介绍功能标签', 32010),
('FUNCTION', 'FUNCTION_INTRODUCTION', 'FUNCTION_INTRODUCE_OTHERS', '介绍他人', '介绍功能标签', 32020),
('FUNCTION', 'FUNCTION_INTRODUCTION', 'FUNCTION_INTRODUCE_OBJECT', '介绍事物', '介绍功能标签', 32030),
('FUNCTION', 'FUNCTION_INTRODUCTION', 'FUNCTION_EXPLAIN_IDENTITY', '说明身份', '介绍功能标签', 32040),
('FUNCTION', null, 'FUNCTION_REASON_LOGIC', '原因逻辑', '功能一级标签', 33000),
('FUNCTION', 'FUNCTION_REASON_LOGIC', 'FUNCTION_EXPLAIN_REASON', '说明原因', '原因逻辑功能标签', 33010),
('FUNCTION', 'FUNCTION_REASON_LOGIC', 'FUNCTION_EXPLAIN_RESULT', '说明结果', '原因逻辑功能标签', 33020),
('FUNCTION', 'FUNCTION_REASON_LOGIC', 'FUNCTION_EXPLAIN_PURPOSE', '说明目的', '原因逻辑功能标签', 33030),
('FUNCTION', 'FUNCTION_REASON_LOGIC', 'FUNCTION_EXPLAIN_CONDITION', '说明条件', '原因逻辑功能标签', 33040),
('FUNCTION', 'FUNCTION_REASON_LOGIC', 'FUNCTION_GIVE_EXAMPLE', '举例', '原因逻辑功能标签', 33050),
('FUNCTION', 'FUNCTION_REASON_LOGIC', 'FUNCTION_SUMMARIZE', '总结', '原因逻辑功能标签', 33060),
('FUNCTION', null, 'FUNCTION_TIME_ACTION', '时间行为', '功能一级标签', 34000),
('FUNCTION', 'FUNCTION_TIME_ACTION', 'FUNCTION_EXPRESS_START', '表达开始', '时间行为功能标签', 34010),
('FUNCTION', 'FUNCTION_TIME_ACTION', 'FUNCTION_EXPRESS_END', '结束', '时间行为功能标签', 34030),
('FUNCTION', 'FUNCTION_TIME_ACTION', 'FUNCTION_EXPRESS_COMPLETION', '完成', '时间行为功能标签', 34040),
('FUNCTION', 'FUNCTION_TIME_ACTION', 'FUNCTION_EXPRESS_EXPERIENCE', '经验', '时间行为功能标签', 34050),
('FUNCTION', 'FUNCTION_TIME_ACTION', 'FUNCTION_EXPRESS_HABIT', '习惯', '时间行为功能标签', 34060),
('FUNCTION', 'FUNCTION_TIME_ACTION', 'FUNCTION_EXPRESS_FREQUENCY', '频率', '时间行为功能标签', 34070),
('FUNCTION', null, 'FUNCTION_ABILITY_OBLIGATION', '能力义务', '功能一级标签', 35000),
('FUNCTION', 'FUNCTION_ABILITY_OBLIGATION', 'FUNCTION_EXPRESS_ABILITY', '表达能力', '能力义务功能标签', 35010),
('FUNCTION', 'FUNCTION_ABILITY_OBLIGATION', 'FUNCTION_EXPRESS_POSSIBILITY', '表达可能', '能力义务功能标签', 35020),
('FUNCTION', 'FUNCTION_ABILITY_OBLIGATION', 'FUNCTION_EXPRESS_OBLIGATION', '表达义务', '能力义务功能标签', 35030),
('FUNCTION', 'FUNCTION_ABILITY_OBLIGATION', 'FUNCTION_EXPRESS_NECESSITY', '表达必要', '能力义务功能标签', 35040),
('FUNCTION', 'FUNCTION_ABILITY_OBLIGATION', 'FUNCTION_EXPRESS_UNNECESSARY', '不必要', '能力义务功能标签', 35050),
('FUNCTION', null, 'FUNCTION_CHOICE_DECISION', '选择决策', '功能一级标签', 36000),
('FUNCTION', 'FUNCTION_CHOICE_DECISION', 'FUNCTION_PROVIDE_CHOICE', '提供选择', '选择决策功能标签', 36010),
('FUNCTION', 'FUNCTION_CHOICE_DECISION', 'FUNCTION_ASK_CHOICE', '询问选择', '选择决策功能标签', 36020),
('FUNCTION', 'FUNCTION_CHOICE_DECISION', 'FUNCTION_EXPRESS_PREFERENCE', '表达偏好', '选择决策功能标签', 36030),
('FUNCTION', 'FUNCTION_CHOICE_DECISION', 'FUNCTION_MAKE_CHOICE', '做出选择', '选择决策功能标签', 36040),
('FUNCTION', 'FUNCTION_CHOICE_DECISION', 'FUNCTION_COMPARE_CHOICES', '比较选择', '选择决策功能标签', 36050),
('FUNCTION', null, 'FUNCTION_NEGOTIATION', '交涉', '功能一级标签', 37000),
('FUNCTION', 'FUNCTION_NEGOTIATION', 'FUNCTION_MAKE_DEMAND', '提出要求', '交涉功能标签', 37010),
('FUNCTION', 'FUNCTION_NEGOTIATION', 'FUNCTION_ACCEPT_CONDITION', '接受条件', '交涉功能标签', 37020),
('FUNCTION', 'FUNCTION_NEGOTIATION', 'FUNCTION_REJECT_CONDITION', '拒绝条件', '交涉功能标签', 37030),
('FUNCTION', 'FUNCTION_NEGOTIATION', 'FUNCTION_NEGOTIATE', '协商', '交涉功能标签', 37040),
('FUNCTION', 'FUNCTION_NEGOTIATION', 'FUNCTION_COMPLAIN', '投诉', '交涉功能标签', 37050),
('FUNCTION', 'FUNCTION_NEGOTIATION', 'FUNCTION_RESPOND_COMPLAINT', '回应投诉', '交涉功能标签', 37060),
('FUNCTION', null, 'FUNCTION_CONVERSATION_MANAGEMENT', '会话管理', '功能一级标签', 38000),
('FUNCTION', 'FUNCTION_CONVERSATION_MANAGEMENT', 'FUNCTION_START_TOPIC', '开启话题', '会话管理功能标签', 38010),
('FUNCTION', 'FUNCTION_CONVERSATION_MANAGEMENT', 'FUNCTION_CHANGE_TOPIC', '转换话题', '会话管理功能标签', 38020),
('FUNCTION', 'FUNCTION_CONVERSATION_MANAGEMENT', 'FUNCTION_CONTINUE_TOPIC', '继续话题', '会话管理功能标签', 38030),
('FUNCTION', 'FUNCTION_CONVERSATION_MANAGEMENT', 'FUNCTION_END_TOPIC', '结束话题', '会话管理功能标签', 38040),
('FUNCTION', 'FUNCTION_CONVERSATION_MANAGEMENT', 'FUNCTION_INTERRUPT', '打断', '会话管理功能标签', 38050),
('FUNCTION', 'FUNCTION_CONVERSATION_MANAGEMENT', 'FUNCTION_REQUEST_REPEAT', '请求重复', '会话管理功能标签', 38060),
('FUNCTION', 'FUNCTION_CONVERSATION_MANAGEMENT', 'FUNCTION_CONFIRM_UNDERSTANDING', '确认理解', '会话管理功能标签', 38070),
('FUNCTION', 'FUNCTION_CONVERSATION_MANAGEMENT', 'FUNCTION_SHOW_UNDERSTANDING', '表示理解', '会话管理功能标签', 38080),
('FUNCTION', null, 'FUNCTION_RELATION_INTERACTION', '关系互动', '功能一级标签', 39000),
('FUNCTION', 'FUNCTION_RELATION_INTERACTION', 'FUNCTION_PRAISE', '称赞', '关系互动功能标签', 39010),
('FUNCTION', 'FUNCTION_RELATION_INTERACTION', 'FUNCTION_ENCOURAGE', '鼓励', '关系互动功能标签', 39020),
('FUNCTION', 'FUNCTION_RELATION_INTERACTION', 'FUNCTION_COMFORT', '安慰', '关系互动功能标签', 39030),
('FUNCTION', 'FUNCTION_RELATION_INTERACTION', 'FUNCTION_SHOW_CARE', '关心', '关系互动功能标签', 39040),
('FUNCTION', 'FUNCTION_RELATION_INTERACTION', 'FUNCTION_BLAME', '责备', '关系互动功能标签', 39050),
('FUNCTION', 'FUNCTION_RELATION_INTERACTION', 'FUNCTION_GRUMBLE', '抱怨', '关系互动功能标签', 39060),
('FUNCTION', 'FUNCTION_RELATION_INTERACTION', 'FUNCTION_JOKE', '开玩笑', '关系互动功能标签', 39070),
('FUNCTION', null, 'FUNCTION_INFO_SEEKING', '信息获取', '功能一级标签', 40000),
('FUNCTION', 'FUNCTION_INFO_SEEKING', 'FUNCTION_ASK_PERSON', '询问人物', '信息获取功能标签', 40010),
('FUNCTION', 'FUNCTION_INFO_SEEKING', 'FUNCTION_ASK_PLACE', '地点', '信息获取功能标签', 40020),
('FUNCTION', 'FUNCTION_INFO_SEEKING', 'FUNCTION_ASK_TIME', '时间', '信息获取功能标签', 40030),
('FUNCTION', 'FUNCTION_INFO_SEEKING', 'FUNCTION_ASK_QUANTITY', '数量', '信息获取功能标签', 40040),
('FUNCTION', 'FUNCTION_INFO_SEEKING', 'FUNCTION_ASK_PRICE', '价格', '信息获取功能标签', 40050),
('FUNCTION', 'FUNCTION_INFO_SEEKING', 'FUNCTION_ASK_METHOD', '方法', '信息获取功能标签', 40060),
('FUNCTION', 'FUNCTION_INFO_SEEKING', 'FUNCTION_ASK_REASON', '原因', '信息获取功能标签', 40070),
('FUNCTION', 'FUNCTION_INFO_SEEKING', 'FUNCTION_ASK_STATUS', '状态', '信息获取功能标签', 40080),
('FUNCTION', null, 'FUNCTION_GENERAL', '泛用', '功能一级标签', 41000),
('FUNCTION', 'FUNCTION_GENERAL', 'FUNCTION_OTHER', '其他', '泛用功能标签', 41010);

insert into tags (
    tag_type,
    parent_id,
    code,
    name,
    description,
    sort_order,
    enabled,
    deleted,
    created_at,
    updated_at
)
select
    tag_type,
    null,
    code,
    name,
    description,
    sort_order,
    true,
    false,
    current_timestamp,
    current_timestamp
from seed_tags
order by sort_order
on conflict (code) do update set
    tag_type = excluded.tag_type,
    parent_id = null,
    name = excluded.name,
    description = excluded.description,
    sort_order = excluded.sort_order,
    enabled = true,
    deleted = false,
    updated_at = current_timestamp;

update tags child
set
    parent_id = parent.id,
    updated_at = current_timestamp
from seed_tags seed
join tags parent on parent.code = seed.parent_code
where child.code = seed.code
  and seed.parent_code is not null
  and child.parent_id is distinct from parent.id;

drop table seed_tags;

insert into tags (
    tag_type,
    parent_id,
    code,
    name,
    description,
    sort_order,
    enabled,
    deleted,
    created_at,
    updated_at
)
values
    ('GENRE', null, 'NARRATIVE', '叙事文', '按时间或事件发展叙述经历和故事', 30000, true, false, current_timestamp, current_timestamp),
    ('GENRE', null, 'EXPOSITORY', '说明文', '说明事物、方法、现象或知识', 30010, true, false, current_timestamp, current_timestamp),
    ('GENRE', null, 'OPINION', '观点文', '表达观点并说明理由', 30020, true, false, current_timestamp, current_timestamp),
    ('GENRE', null, 'PRACTICAL', '实用文', '通知、邮件、报告等实际用途文章', 30030, true, false, current_timestamp, current_timestamp),
    ('GENRE', null, 'ESSAY', '随笔', '围绕见闻、感受和思考自由展开', 30040, true, false, current_timestamp, current_timestamp),
    ('GENRE', null, 'DIARY', '日记', '记录特定时间的经历、情绪和想法', 30050, true, false, current_timestamp, current_timestamp),
    ('GENRE', null, 'DIALOGUE', '对话', '以人物对话推动信息交流或冲突', 30060, true, false, current_timestamp, current_timestamp),
    ('GENRE', null, 'NEWS_REPORT', '新闻报道', '客观报道事件、影响和应对', 30070, true, false, current_timestamp, current_timestamp),
    ('GENRE', null, 'INTERVIEW', '访谈', '通过问答呈现受访者经历和观点', 30080, true, false, current_timestamp, current_timestamp),
    ('GENRE', null, 'REVIEW', '评测', '评价产品、作品、服务或体验', 30090, true, false, current_timestamp, current_timestamp),
    ('GENRE', null, 'GUIDE', '指南', '面向目标人群提供步骤和实用建议', 30100, true, false, current_timestamp, current_timestamp),
    ('GENRE', null, 'FICTION', '小说', '通过虚构人物、环境和冲突展开内容', 30110, true, false, current_timestamp, current_timestamp)
on conflict (code) do update set
    tag_type = excluded.tag_type,
    parent_id = excluded.parent_id,
    name = excluded.name,
    description = excluded.description,
    sort_order = excluded.sort_order,
    enabled = true,
    deleted = false,
    updated_at = current_timestamp;

create extension if not exists vector;

create table if not exists questions (
    id bigint generated by default as identity primary key,
    question_type varchar(32) not null default 'TRANSLATION_ZH_TO_JA',
    source_text text not null,
    context_text text null,
    level varchar(8) null,
    difficulty smallint not null default 3,
    grammar_point varchar(255) null,
    spoken boolean not null default false,
    business boolean not null default false,
    exam boolean not null default false,
    source_type varchar(32) not null default 'AI',
    enabled boolean not null default true,
    deleted boolean not null default false,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,

    constraint ck_questions_type check (question_type in ('TRANSLATION_ZH_TO_JA', 'TRANSLATION_ZH_TO_JA_ARTICLE')),
    constraint ck_questions_level check (level is null or level in ('N5', 'N4', 'N3', 'N2', 'N1')),
    constraint ck_questions_difficulty check (difficulty between 1 and 5),
    constraint ck_questions_source_type check (source_type in ('AI', 'MANUAL', 'REVIEW_DERIVED'))
);

alter table questions drop constraint if exists ck_questions_source_type;
alter table questions
    add constraint ck_questions_source_type
    check (source_type in ('AI', 'MANUAL', 'REVIEW_DERIVED'));

alter table questions drop constraint if exists ck_questions_type;
alter table questions
    add constraint ck_questions_type
    check (question_type in ('TRANSLATION_ZH_TO_JA', 'TRANSLATION_ZH_TO_JA_ARTICLE'));

comment on table questions is '题目表';
comment on column questions.id is '主键ID';
comment on column questions.question_type is '题目类型：TRANSLATION_ZH_TO_JA=中译日短句，TRANSLATION_ZH_TO_JA_ARTICLE=中译日文章';
comment on column questions.source_text is '中文题目原文，文章题按句使用双换行分隔';
comment on column questions.context_text is '题目语境说明';
comment on column questions.level is 'JLPT等级：N5、N4、N3、N2、N1';
comment on column questions.difficulty is '难度等级，范围1到5';
comment on column questions.grammar_point is '短句语法点或文章生词提示';
comment on column questions.spoken is '是否口语表达';
comment on column questions.business is '是否商务表达';
comment on column questions.exam is '是否考试相关';
comment on column questions.source_type is '题目来源：AI=AI生成，MANUAL=人工录入，REVIEW_DERIVED=复习衍生题';
comment on column questions.enabled is '是否启用';
comment on column questions.deleted is '是否删除';
comment on column questions.created_at is '创建时间';
comment on column questions.updated_at is '更新时间';

create index if not exists idx_questions_type on questions (question_type);
create index if not exists idx_questions_level on questions (level);
create index if not exists idx_questions_difficulty on questions (difficulty);
create index if not exists idx_questions_source_type on questions (source_type);
create index if not exists idx_questions_enabled_deleted on questions (enabled, deleted);

create table if not exists question_embeddings (
    question_id bigint primary key references questions(id),
    embedding vector(768) not null,
    content_hash char(64) not null,
    model_name varchar(128) not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

comment on table question_embeddings is '题目语义向量表，仅用于常规题生成去重';
comment on column question_embeddings.question_id is '题目ID';
comment on column question_embeddings.embedding is '768维语义向量';
comment on column question_embeddings.content_hash is '向量输入内容哈希，文章仅使用正文，短句使用原文和语境';
comment on column question_embeddings.model_name is '嵌入模型名称';

create index if not exists idx_question_embeddings_embedding_hnsw
    on question_embeddings using hnsw (embedding vector_cosine_ops);

create table if not exists article_generation_metadata (
    question_id bigint primary key references questions(id),
    seed uuid not null unique,
    blueprint jsonb not null,
    created_at timestamp not null default current_timestamp,
    constraint ck_article_generation_metadata_blueprint check (
        jsonb_typeof(blueprint) = 'object'
        and blueprint ? 'coreConcept'
        and jsonb_typeof(blueprint -> 'roles') = 'object'
    )
);

comment on table article_generation_metadata is 'AI文章生成蓝图元数据表';
comment on column article_generation_metadata.question_id is '文章题目ID，与questions一对一';
comment on column article_generation_metadata.seed is '最终成功尝试使用的随机UUID种子';
comment on column article_generation_metadata.blueprint is '最终成功生成的核心概念和语义角色';

create table if not exists question_answers (
    id bigint generated by default as identity primary key,
    question_id bigint not null,
    answer_text text not null,
    answer_type varchar(32) not null default 'STANDARD',
    primary_answer boolean not null default false,
    sort_order integer not null default 0,
    deleted boolean not null default false,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,

    constraint ck_question_answers_type check (answer_type in ('STANDARD', 'REFERENCE'))
);

comment on table question_answers is '题目答案表';
comment on column question_answers.id is '主键ID';
comment on column question_answers.question_id is '题目ID，对应 questions.id，由代码维护有效性';
comment on column question_answers.answer_text is '答案文本，当前为日语表达';
comment on column question_answers.answer_type is '答案类型：STANDARD=标准答案，REFERENCE=参考答案';
comment on column question_answers.primary_answer is '是否主答案';
comment on column question_answers.sort_order is '排序值，数值越小越靠前';
comment on column question_answers.deleted is '是否删除';
comment on column question_answers.created_at is '创建时间';
comment on column question_answers.updated_at is '更新时间';

create index if not exists idx_question_answers_question_id on question_answers (question_id);
create index if not exists idx_question_answers_deleted on question_answers (deleted);
create unique index if not exists uq_question_answers_primary
    on question_answers (question_id)
    where primary_answer = true and deleted = false;
create unique index if not exists uq_question_answers_active_text
    on question_answers (question_id, answer_text)
    where deleted = false;

create table if not exists users (
    id bigint generated by default as identity primary key,
    user_code varchar(64) not null,
    nickname varchar(64) not null,
    user_type varchar(32) not null default 'LOCAL',
    enabled boolean not null default true,
    deleted boolean not null default false,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,

    constraint uq_users_user_code unique (user_code),
    constraint ck_users_user_type check (user_type in ('LOCAL', 'REGISTERED')),
    constraint ck_users_user_code_not_blank check (length(trim(user_code)) > 0),
    constraint ck_users_nickname_not_blank check (length(trim(nickname)) > 0)
);

comment on table users is '用户表';
comment on column users.id is '主键ID';
comment on column users.user_code is '用户编码，本地用户或后续账号用户的稳定标识';
comment on column users.nickname is '用户昵称';
comment on column users.user_type is '用户类型：LOCAL=本地用户，REGISTERED=注册用户';
comment on column users.enabled is '是否启用';
comment on column users.deleted is '是否删除';
comment on column users.created_at is '创建时间';
comment on column users.updated_at is '更新时间';

create index if not exists idx_users_user_type on users (user_type);
create index if not exists idx_users_enabled_deleted on users (enabled, deleted);

insert into users (
    user_code,
    nickname,
    user_type,
    enabled,
    deleted,
    created_at,
    updated_at
)
values (
    'LOCAL_DEFAULT',
    '本地用户',
    'LOCAL',
    true,
    false,
    current_timestamp,
    current_timestamp
)
on conflict (user_code) do update set
    nickname = excluded.nickname,
    user_type = excluded.user_type,
    enabled = true,
    deleted = false,
    updated_at = current_timestamp;

create table if not exists user_answers (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    question_id bigint not null,
    answer_text text not null,
    answer_status varchar(32) not null default 'SUBMITTED',
    grammar_vocabulary_score smallint null,
    natural_fluency_score smallint null,
    scenario_adaptation_score smallint null,
    information_completeness_score smallint null,
    total_score numeric(5, 2) null,
    ai_overall_comment text null,
    ai_revised_text text null,
    deleted boolean not null default false,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,

    constraint ck_user_answers_status check (answer_status in ('SUBMITTED', 'REVIEWED', 'FAILED')),
    constraint ck_user_answers_answer_text_not_blank check (length(trim(answer_text)) > 0),
    constraint ck_user_answers_grammar_vocabulary_score check (
        grammar_vocabulary_score is null or grammar_vocabulary_score between 0 and 100
    ),
    constraint ck_user_answers_natural_fluency_score check (
        natural_fluency_score is null or natural_fluency_score between 0 and 100
    ),
    constraint ck_user_answers_scenario_adaptation_score check (
        scenario_adaptation_score is null or scenario_adaptation_score between 0 and 100
    ),
    constraint ck_user_answers_information_completeness_score check (
        information_completeness_score is null or information_completeness_score between 0 and 100
    ),
    constraint ck_user_answers_total_score check (
        total_score is null or total_score between 0 and 100
    ),
    constraint ck_user_answers_question_or_correction check (
        question_id is not null or ai_revised_text is not null
    )
);

alter table user_answers alter column question_id drop not null;
alter table user_answers add column if not exists ai_revised_text text null;
alter table user_answers drop constraint if exists ck_user_answers_question_or_correction;
alter table user_answers add constraint ck_user_answers_question_or_correction check (
    question_id is not null or ai_revised_text is not null
);

comment on table user_answers is '用户回答表';
comment on column user_answers.id is '主键ID';
comment on column user_answers.user_id is '用户ID，对应 users.id，由代码维护有效性';
comment on column user_answers.question_id is '题目ID，对应 questions.id，由代码维护有效性；纯日语纠错记录为空';
comment on column user_answers.answer_text is '用户提交的日语答案';
comment on column user_answers.answer_status is '回答状态：SUBMITTED=已提交，REVIEWED=已评测，FAILED=评测失败';
comment on column user_answers.grammar_vocabulary_score is '语法与词汇正确性评分，满分100分';
comment on column user_answers.natural_fluency_score is '自然度与流畅度评分，满分100分';
comment on column user_answers.scenario_adaptation_score is '场景适配度评分，满分100分';
comment on column user_answers.information_completeness_score is '表达信息完整性评分，满分100分';
comment on column user_answers.total_score is '总分，四项评分均值，由代码计算';
comment on column user_answers.ai_overall_comment is 'AI总体评价';
comment on column user_answers.ai_revised_text is 'AI修订后的完整日语文本，纯日语纠错记录使用';
comment on column user_answers.deleted is '是否删除';
comment on column user_answers.created_at is '创建时间';
comment on column user_answers.updated_at is '更新时间';

create index if not exists idx_user_answers_user_id on user_answers (user_id);
create index if not exists idx_user_answers_question_id on user_answers (question_id);
create index if not exists idx_user_answers_user_question on user_answers (user_id, question_id);
create index if not exists idx_user_answers_status on user_answers (answer_status);
create index if not exists idx_user_answers_total_score on user_answers (total_score);
create index if not exists idx_user_answers_created_at on user_answers (created_at);
create index if not exists idx_user_answers_deleted on user_answers (deleted);
create index if not exists idx_user_answers_user_created_at_active
    on user_answers (user_id, created_at)
    where deleted = false;

create table if not exists error_types (
    id bigint generated by default as identity primary key,
    parent_id bigint null,
    type_level smallint not null,
    code varchar(64) not null,
    name varchar(64) not null,
    description varchar(255) null,
    sort_order integer not null default 0,
    enabled boolean not null default true,
    deleted boolean not null default false,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,

    constraint uq_error_types_code unique (code),
    constraint ck_error_types_level check (type_level in (1, 2)),
    constraint ck_error_types_parent check (
        (type_level = 1 and parent_id is null)
        or (type_level = 2 and parent_id is not null)
    ),
    constraint ck_error_types_parent_not_self check (parent_id is null or parent_id <> id),
    constraint ck_error_types_sort_order check (sort_order >= 0)
);

comment on table error_types is '错误类型表';
comment on column error_types.id is '主键ID';
comment on column error_types.parent_id is '父级错误类型ID，对应 error_types.id，由代码维护有效性';
comment on column error_types.type_level is '类型层级：1=一级分类，2=二级分类';
comment on column error_types.code is '错误类型编码，全局唯一';
comment on column error_types.name is '错误类型名称';
comment on column error_types.description is '错误类型说明';
comment on column error_types.sort_order is '排序值，数值越小越靠前';
comment on column error_types.enabled is '是否启用';
comment on column error_types.deleted is '是否逻辑删除';
comment on column error_types.created_at is '创建时间';
comment on column error_types.updated_at is '更新时间';

create index if not exists idx_error_types_parent_id on error_types (parent_id);
create index if not exists idx_error_types_enabled_deleted on error_types (enabled, deleted);

insert into error_types (
    parent_id,
    type_level,
    code,
    name,
    description,
    sort_order,
    enabled,
    deleted,
    created_at,
    updated_at
)
values
    (null, 1, 'SEMANTIC', '语义与信息完整性', '含义传达和信息保留方面的错误', 1000, true, false, current_timestamp, current_timestamp),
    (null, 1, 'LEXICAL_EXPRESSION', '词汇与表达自然度', '词义、搭配和表达自然度方面的错误', 2000, true, false, current_timestamp, current_timestamp),
    (null, 1, 'GRAMMAR_SYNTAX', '语法与句法', '语法结构、助词和动词使用方面的错误', 3000, true, false, current_timestamp, current_timestamp),
    (null, 1, 'PRAGMATICS_CONTEXT', '语用与场景适配', '敬语、语体和场景适配方面的错误', 4000, true, false, current_timestamp, current_timestamp),
    (null, 1, 'WRITING_FORMAT', '书写与格式', '假名、汉字和书写格式方面的错误', 5000, true, false, current_timestamp, current_timestamp)
on conflict (code) do nothing;

insert into error_types (
    parent_id,
    type_level,
    code,
    name,
    description,
    sort_order,
    enabled,
    deleted,
    created_at,
    updated_at
)
select
    parent.id,
    2,
    seed.code,
    seed.name,
    seed.description,
    seed.sort_order,
    true,
    false,
    current_timestamp,
    current_timestamp
from (
    values
        ('SEMANTIC', 'OMISSION', '漏译', '遗漏原文中的必要信息', 1010),
        ('SEMANTIC', 'MISTRANSLATION', '误译', '对原文含义的理解或翻译错误', 1020),
        ('SEMANTIC', 'ADDITION', '过度发挥', '加入原文没有的信息', 1030),
        ('SEMANTIC', 'SUBJECT_OBJECT', '主语或对象错误', '人物、对象或动作归属错误', 1040),
        ('SEMANTIC', 'LOGIC_RELATION', '逻辑关系错误', '因果、转折、条件等逻辑关系错误', 1050),
        ('LEXICAL_EXPRESSION', 'WORD_SENSE', '词义混淆', '未按语境选择正确词义', 2010),
        ('LEXICAL_EXPRESSION', 'SYNONYM', '近义词误用', '近义词的语义范围或使用条件不符', 2020),
        ('LEXICAL_EXPRESSION', 'COLLOCATION', '搭配错误', '词语组合不符合日语常用搭配', 2030),
        ('LEXICAL_EXPRESSION', 'FALSE_FRIEND', '中日同形词误用', '误按中文含义使用日语同形词', 2040),
        ('LEXICAL_EXPRESSION', 'CHINESE_CALQUE', '中文直译', '直接套用中文表达导致不自然', 2050),
        ('LEXICAL_EXPRESSION', 'WORD_ORDER', '语序生硬', '语序可理解但不符合自然日语习惯', 2060),
        ('LEXICAL_EXPRESSION', 'REDUNDANCY', '冗余表达', '存在不必要的重复或累赘表达', 2070),
        ('LEXICAL_EXPRESSION', 'UNNATURAL_EXPRESSION', '不自然表达', '语义正确但整体表达不地道', 2080),
        ('GRAMMAR_SYNTAX', 'SENTENCE_PATTERN', '句型错误', '句型选择或结构不正确', 3010),
        ('GRAMMAR_SYNTAX', 'CONJUGATION', '活用错误', '动词、形容词或助动词活用错误', 3020),
        ('GRAMMAR_SYNTAX', 'CONNECTION', '接续错误', '词语或句子之间的接续形式错误', 3030),
        ('GRAMMAR_SYNTAX', 'NEGATION', '否定表达错误', '否定形式或否定范围使用错误', 3040),
        ('GRAMMAR_SYNTAX', 'CONDITION', '条件表达错误', '条件句型或条件关系使用错误', 3050),
        ('GRAMMAR_SYNTAX', 'PARTICLE', '助词错误', '助词的选择、位置或语义功能错误', 3060),
        ('GRAMMAR_SYNTAX', 'TENSE_ASPECT', '时态体貌错误', '时态、持续、完成或状态表达错误', 3070),
        ('GRAMMAR_SYNTAX', 'TRANSITIVE_INTRANSITIVE', '自他动词错误', '自动词和他动词的选择或格助词搭配错误', 3080),
        ('GRAMMAR_SYNTAX', 'GIVING_RECEIVING', '授受关系错误', '授受动词或受益关系表达错误', 3090),
        ('PRAGMATICS_CONTEXT', 'POLITENESS', '礼貌程度错误', '礼貌程度与交际关系不匹配', 4010),
        ('PRAGMATICS_CONTEXT', 'HONORIFIC', '尊敬语错误', '对对方或第三方的尊敬语使用错误', 4020),
        ('PRAGMATICS_CONTEXT', 'HUMBLE', '谦让语错误', '对己方行为的谦让语使用错误', 4030),
        ('PRAGMATICS_CONTEXT', 'STYLE_CONSISTENCY', '语体不一致', '普通体、敬体或书面语体前后混用', 4040),
        ('PRAGMATICS_CONTEXT', 'FORMALITY', '正式程度错误', '表达正式程度与场景不匹配', 4050),
        ('PRAGMATICS_CONTEXT', 'ADDRESSEE', '对象身份不匹配', '未根据说话对象选择合适表达', 4060),
        ('WRITING_FORMAT', 'KANA', '假名错误', '平假名、片假名或假名拼写错误', 5010),
        ('WRITING_FORMAT', 'KANJI', '汉字错误', '汉字选择、写法或读写对应错误', 5020),
        ('WRITING_FORMAT', 'ORTHOGRAPHY', '表记错误', '长音、促音、送假名等表记错误', 5030),
        ('WRITING_FORMAT', 'PUNCTUATION', '标点错误', '标点符号或断句方式不恰当', 5040),
        ('WRITING_FORMAT', 'INCOMPLETE_INPUT', '输入残缺', '答案存在缺字、截断或未完成输入', 5050)
) as seed(parent_code, code, name, description, sort_order)
inner join error_types parent
    on parent.code = seed.parent_code
   and parent.type_level = 1
   and parent.deleted = false
on conflict (code) do nothing;

create table if not exists user_error_types (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    error_type_id bigint not null,
    name varchar(128) not null,
    description varchar(255) null,
    status varchar(16) not null default 'ACTIVE',
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,

    constraint ck_user_error_types_name_not_blank check (length(trim(name)) > 0),
    constraint ck_user_error_types_status check (status in ('ACTIVE', 'ARCHIVED'))
);

comment on table user_error_types is '用户错误类型表';
comment on column user_error_types.id is '主键ID';
comment on column user_error_types.user_id is '用户ID，对应 users.id，由代码维护有效性';
comment on column user_error_types.error_type_id is '二级错误类型ID，对应 error_types.id，由代码维护有效性';
comment on column user_error_types.name is '用户定义的错误类型名称';
comment on column user_error_types.description is '用户错误类型说明';
comment on column user_error_types.status is '错误类型状态：ACTIVE=进行中，ARCHIVED=已归档';
comment on column user_error_types.created_at is '创建时间';
comment on column user_error_types.updated_at is '更新时间';

create index if not exists idx_user_error_types_user_status on user_error_types (user_id, status);
create unique index if not exists uq_user_error_types_user_type_name
    on user_error_types (user_id, error_type_id, name)
    where status = 'ACTIVE';

create table if not exists user_answer_errors (
    id bigint generated by default as identity primary key,
    user_answer_id bigint not null,
    user_id bigint not null,
    question_id bigint not null,
    error_type_id bigint not null,
    user_error_type_id bigint null,
    original_text text not null,
    issue text not null,
    suggestion text not null,
    severity varchar(16) not null,
    sort_order integer not null default 0,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,

    constraint ck_user_answer_errors_original_text_not_blank check (length(trim(original_text)) > 0),
    constraint ck_user_answer_errors_issue_not_blank check (length(trim(issue)) > 0),
    constraint ck_user_answer_errors_suggestion_not_blank check (length(trim(suggestion)) > 0),
    constraint ck_user_answer_errors_severity check (severity in ('LOW', 'MEDIUM', 'HIGH')),
    constraint ck_user_answer_errors_sort_order check (sort_order >= 0)
);

alter table user_answer_errors alter column question_id drop not null;

comment on table user_answer_errors is '用户回答错误记录表';
comment on column user_answer_errors.id is '主键ID';
comment on column user_answer_errors.user_answer_id is '用户回答ID，对应 user_answers.id，由代码维护有效性';
comment on column user_answer_errors.user_id is '用户ID，冗余保存自 user_answers.user_id';
comment on column user_answer_errors.question_id is '题目ID，冗余保存自 user_answers.question_id；纯日语纠错记录为空';
comment on column user_answer_errors.error_type_id is '二级错误类型ID，对应 error_types.id，由代码维护有效性';
comment on column user_answer_errors.user_error_type_id is '用户错误类型ID，对应 user_error_types.id，由代码维护有效性';
comment on column user_answer_errors.original_text is '用户答案中的错误片段';
comment on column user_answer_errors.issue is '错误问题说明';
comment on column user_answer_errors.suggestion is '修改建议';
comment on column user_answer_errors.severity is '错误严重程度：LOW=轻微，MEDIUM=中等，HIGH=严重';
comment on column user_answer_errors.sort_order is '同一次回答中的展示排序';
comment on column user_answer_errors.created_at is '创建时间';
comment on column user_answer_errors.updated_at is '更新时间';

create index if not exists idx_user_answer_errors_user_answer_id on user_answer_errors (user_answer_id);
create index if not exists idx_user_answer_errors_user_error_type_created_at on user_answer_errors (user_id, error_type_id, created_at);
create index if not exists idx_user_answer_errors_user_question on user_answer_errors (user_id, question_id);
create index if not exists idx_user_answer_errors_error_type_id on user_answer_errors (error_type_id);
create index if not exists idx_user_answer_errors_user_error_type_id on user_answer_errors (user_error_type_id);
create index if not exists idx_user_answer_errors_user_error_type_question
    on user_answer_errors (user_error_type_id, question_id);
create index if not exists idx_user_answer_errors_user_created_at
    on user_answer_errors (user_id, created_at);

create table if not exists review_cards (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    user_error_type_id bigint not null,
    status varchar(16) not null default 'ACTIVE',
    ease_factor numeric(5, 4) not null default 2.5000,
    repetition_count integer not null default 0,
    interval_days integer not null default 1,
    lapse_count integer not null default 0,
    due_at timestamp null,
    last_reviewed_at timestamp null,
    mastered_at timestamp null,
    deleted boolean not null default false,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,

    constraint uq_review_cards_user_error_type unique (user_error_type_id),
    constraint ck_review_cards_status check (status in ('ACTIVE', 'MASTERED')),
    constraint ck_review_cards_ease_factor check (ease_factor >= 1.3000),
    constraint ck_review_cards_repetition_count check (repetition_count >= 0),
    constraint ck_review_cards_interval_days check (interval_days >= 1),
    constraint ck_review_cards_lapse_count check (lapse_count >= 0),
    constraint ck_review_cards_status_time check (
        (status = 'ACTIVE' and due_at is not null and mastered_at is null)
        or (status = 'MASTERED' and due_at is null and mastered_at is not null)
    )
);

comment on table review_cards is '用户错误类型复习卡片表';
comment on column review_cards.id is '复习卡片主键ID';
comment on column review_cards.user_id is '卡片所属用户ID，对应 users.id，由代码维护有效性';
comment on column review_cards.user_error_type_id is '用户错误类型ID，对应 user_error_types.id，一种用户错误类型只有一张卡片';
comment on column review_cards.status is '卡片状态：ACTIVE=复习中或等待到期，MASTERED=当前周期已完成并已掌握';
comment on column review_cards.ease_factor is 'SM-2难度因子，默认2.5000，最低1.3000';
comment on column review_cards.repetition_count is '当前连续成功次数，复习失败时归零';
comment on column review_cards.interval_days is '当前SM-2复习间隔天数，失败后重置为1天';
comment on column review_cards.lapse_count is '累计失败次数，包含复习失败和普通练习再次确认同类错误';
comment on column review_cards.due_at is '下次应复习时间，已掌握时为空';
comment on column review_cards.last_reviewed_at is '最近一次影响卡片SM-2状态的时间';
comment on column review_cards.mastered_at is '最近一次完成复习周期并标记掌握的时间，重新激活时清空';
comment on column review_cards.deleted is '逻辑删除标记：false=未删除，true=已删除';
comment on column review_cards.created_at is '创建时间';
comment on column review_cards.updated_at is '更新时间';

create index if not exists idx_review_cards_user_status_due_at
    on review_cards (user_id, deleted, status, due_at);

create table if not exists review_cycles (
    id bigint generated by default as identity primary key,
    review_card_id bigint not null,
    cycle_no integer not null,
    status varchar(16) not null default 'IN_PROGRESS',
    target_success_count integer not null default 4,
    successful_review_count integer not null default 0,
    failed_review_count integer not null default 0,
    verification_required_after timestamp not null default current_timestamp,
    started_at timestamp not null default current_timestamp,
    completed_at timestamp null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,

    constraint uq_review_cycles_card_cycle_no unique (review_card_id, cycle_no),
    constraint ck_review_cycles_cycle_no check (cycle_no >= 1),
    constraint ck_review_cycles_status check (status in ('IN_PROGRESS', 'COMPLETED')),
    constraint ck_review_cycles_target_success_count check (target_success_count = 4),
    constraint ck_review_cycles_successful_review_count check (successful_review_count >= 0),
    constraint ck_review_cycles_failed_review_count check (failed_review_count >= 0),
    constraint ck_review_cycles_status_time check (
        (status = 'IN_PROGRESS' and completed_at is null)
        or (status = 'COMPLETED' and completed_at is not null)
    )
);

alter table review_cycles
    add column if not exists failed_review_count integer not null default 0;
alter table review_cycles drop constraint if exists ck_review_cycles_failed_review_count;
alter table review_cycles
    add constraint ck_review_cycles_failed_review_count check (failed_review_count >= 0);

comment on table review_cycles is '复习卡片周期表';
comment on column review_cycles.id is '复习周期主键ID';
comment on column review_cycles.review_card_id is '所属复习卡片ID，对应 review_cards.id，由代码维护有效性';
comment on column review_cycles.cycle_no is '卡片周期序号，从1开始递增';
comment on column review_cycles.status is '周期状态：IN_PROGRESS=进行中，COMPLETED=已完成';
comment on column review_cycles.target_success_count is '本周期目标净成功次数，固定为4';
comment on column review_cycles.successful_review_count is '本周期累计成功作答次数，失败时不清零';
comment on column review_cycles.failed_review_count is '本周期累计失败次数，不包含创建新卡片的首次错误';
comment on column review_cycles.verification_required_after is '兼容字段，记录最近新增或再次答错原题的时间';
comment on column review_cycles.started_at is '周期开始时间';
comment on column review_cycles.completed_at is '周期完成时间，进行中时为空';
comment on column review_cycles.created_at is '创建时间';
comment on column review_cycles.updated_at is '更新时间';

create unique index if not exists uq_review_cycles_in_progress_card
    on review_cycles (review_card_id)
    where status = 'IN_PROGRESS';
create index if not exists idx_review_cycles_card_status
    on review_cycles (review_card_id, status);

create table if not exists review_cycle_questions (
    id bigint generated by default as identity primary key,
    review_cycle_id bigint not null,
    question_id bigint not null,
    question_role varchar(16) not null,
    review_status varchar(16) not null default 'PENDING',
    attempt_count integer not null default 0,
    last_quality smallint null,
    last_attempt_at timestamp null,
    passed_at timestamp null,
    sort_order integer not null default 0,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,

    constraint uq_review_cycle_questions_cycle_question unique (review_cycle_id, question_id),
    constraint ck_review_cycle_questions_role check (question_role in ('ORIGINAL', 'DERIVED')),
    constraint ck_review_cycle_questions_status check (review_status in ('PENDING', 'RETRY', 'PASSED')),
    constraint ck_review_cycle_questions_attempt_count check (attempt_count >= 0),
    constraint ck_review_cycle_questions_last_quality check (last_quality is null or last_quality between 0 and 5),
    constraint ck_review_cycle_questions_sort_order check (sort_order >= 0),
    constraint ck_review_cycle_questions_status_time check (
        (review_status = 'PASSED' and passed_at is not null)
        or (review_status in ('PENDING', 'RETRY') and passed_at is null)
    )
);

comment on table review_cycle_questions is '复习周期题目表';
comment on column review_cycle_questions.id is '周期题目主键ID';
comment on column review_cycle_questions.review_cycle_id is '所属复习周期ID，对应 review_cycles.id，由代码维护有效性';
comment on column review_cycle_questions.question_id is '实际题目ID，对应 questions.id，原题和衍生题统一使用题目表';
comment on column review_cycle_questions.question_role is '题目角色：ORIGINAL=错误记录关联原题，DERIVED=AI生成复习衍生题';
comment on column review_cycle_questions.review_status is '复习状态：PENDING=尚未作答，RETRY=失败后等待重试，PASSED=本周期已通过';
comment on column review_cycle_questions.attempt_count is '该题在本周期的总作答次数';
comment on column review_cycle_questions.last_quality is '最近一次SM-2质量分，范围0到5，尚未作答时为空';
comment on column review_cycle_questions.last_attempt_at is '最近作答时间，多个重试题按该时间倒序选择';
comment on column review_cycle_questions.passed_at is '最近一次通过时间，再次失败时清空，历史通过保留在复习事件表';
comment on column review_cycle_questions.sort_order is '同优先级题目的稳定排序值';
comment on column review_cycle_questions.created_at is '加入本周期的时间';
comment on column review_cycle_questions.updated_at is '更新时间';

create unique index if not exists uq_review_cycle_questions_derived_owner
    on review_cycle_questions (question_id)
    where question_role = 'DERIVED';
create unique index if not exists uq_review_cycle_questions_active_derived
    on review_cycle_questions (review_cycle_id)
    where question_role = 'DERIVED' and review_status in ('PENDING', 'RETRY');
create index if not exists idx_review_cycle_questions_cycle_status_attempt
    on review_cycle_questions (review_cycle_id, review_status, last_attempt_at desc);
create index if not exists idx_review_cycle_questions_question_id
    on review_cycle_questions (question_id);

create table if not exists review_attempts (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    review_card_id bigint not null,
    review_cycle_id bigint not null,
    review_cycle_question_id bigint not null,
    user_answer_id bigint not null,
    attempt_source varchar(24) not null,
    result varchar(16) not null,
    sm2_quality smallint not null,
    target_error_resolved boolean not null,
    ai_feedback text null,
    ease_factor_after numeric(5, 4) not null,
    repetition_count_after integer not null,
    interval_days_after integer not null,
    cycle_success_count_after integer not null,
    next_due_at timestamp null,
    created_at timestamp not null default current_timestamp,

    constraint uq_review_attempts_card_user_answer unique (review_card_id, user_answer_id),
    constraint ck_review_attempts_source check (attempt_source in ('REVIEW', 'PRACTICE_ERROR')),
    constraint ck_review_attempts_result check (result in ('PASS', 'FAIL')),
    constraint ck_review_attempts_quality check (sm2_quality between 0 and 5),
    constraint ck_review_attempts_result_quality check (
        (result = 'PASS' and sm2_quality between 3 and 5 and target_error_resolved = true)
        or (result = 'FAIL' and sm2_quality between 0 and 2 and target_error_resolved = false)
    ),
    constraint ck_review_attempts_practice_error check (
        attempt_source <> 'PRACTICE_ERROR'
        or (result = 'FAIL' and sm2_quality = 2 and target_error_resolved = false)
    ),
    constraint ck_review_attempts_ease_factor check (ease_factor_after >= 1.3000),
    constraint ck_review_attempts_repetition_count check (repetition_count_after >= 0),
    constraint ck_review_attempts_interval_days check (interval_days_after >= 1),
    constraint ck_review_attempts_cycle_success_count check (cycle_success_count_after >= 0),
    constraint ck_review_attempts_fail_due_at check (result <> 'FAIL' or next_due_at is not null)
);

comment on table review_attempts is '复习作答事件表';
comment on column review_attempts.id is '复习事件主键ID';
comment on column review_attempts.user_id is '作答用户ID，对应 users.id，冗余保存用于用户维度统计';
comment on column review_attempts.review_card_id is '本次事件影响的复习卡片ID，对应 review_cards.id';
comment on column review_attempts.review_cycle_id is '本次事件所属复习周期ID，对应 review_cycles.id';
comment on column review_attempts.review_cycle_question_id is '本次事件对应周期题目ID，对应 review_cycle_questions.id';
comment on column review_attempts.user_answer_id is '实际用户答案ID，对应 user_answers.id';
comment on column review_attempts.attempt_source is '事件来源：REVIEW=复习作答，PRACTICE_ERROR=普通练习确认同类错误';
comment on column review_attempts.result is '复习结果：PASS=通过，FAIL=失败';
comment on column review_attempts.sm2_quality is 'SM-2质量分，范围0到5，普通练习确认同类错误固定为2';
comment on column review_attempts.target_error_resolved is '本次回答是否解决卡片针对的目标错误';
comment on column review_attempts.ai_feedback is '复习专用AI评分反馈，普通练习失败事件可以为空';
comment on column review_attempts.ease_factor_after is '处理本次事件后的SM-2难度因子';
comment on column review_attempts.repetition_count_after is '处理本次事件后的连续成功次数';
comment on column review_attempts.interval_days_after is '处理本次事件后的复习间隔天数';
comment on column review_attempts.cycle_success_count_after is '处理本次事件后的周期累计成功次数';
comment on column review_attempts.next_due_at is '本次事件计算出的下次复习时间，完成周期时为空';
comment on column review_attempts.created_at is '事件发生时间，事件记录创建后不再更新';

create index if not exists idx_review_attempts_card_created_at
    on review_attempts (review_card_id, created_at);
create index if not exists idx_review_attempts_user_answer_id
    on review_attempts (user_answer_id);
create index if not exists idx_review_attempts_user_created_at
    on review_attempts (user_id, created_at);

update review_cycles
set target_success_count = 4
where target_success_count <> 4;

alter table review_cycles drop constraint if exists ck_review_cycles_target_success_count;
alter table review_cycles
    add constraint ck_review_cycles_target_success_count check (target_success_count = 4);

update review_cycles cycle
set failed_review_count = (
    select count(*)::integer
    from review_attempts attempt
    where attempt.review_cycle_id = cycle.id
      and attempt.result = 'FAIL'
      and not (
          attempt.attempt_source = 'PRACTICE_ERROR'
          and cycle.cycle_no = 1
          and attempt.created_at = cycle.started_at
          and attempt.id = (
              select min(first_attempt.id)
              from review_attempts first_attempt
              where first_attempt.review_cycle_id = cycle.id
          )
      )
)
where cycle.status = 'IN_PROGRESS';

update review_cards
set due_at = due_at::date + time '07:00',
    updated_at = current_timestamp
where status = 'ACTIVE'
  and due_at is not null
  and due_at::time <> time '07:00';

with completable_cycles as (
    select cycle.id, cycle.review_card_id
    from review_cycles cycle
    inner join review_cards card
        on card.id = cycle.review_card_id
       and card.status = 'ACTIVE'
    where cycle.status = 'IN_PROGRESS'
      and cycle.successful_review_count - cycle.failed_review_count >= cycle.target_success_count
      and exists (
          select 1
          from review_cycle_questions question
          where question.review_cycle_id = cycle.id
            and question.question_role = 'ORIGINAL'
      )
      and not exists (
          select 1
          from review_cycle_questions question
          where question.review_cycle_id = cycle.id
            and (
                (question.question_role = 'ORIGINAL' and question.review_status <> 'PASSED')
                or question.review_status in ('PENDING', 'RETRY')
            )
      )
)
update review_cards card
set status = 'MASTERED',
    due_at = null,
    mastered_at = current_timestamp,
    updated_at = current_timestamp
from completable_cycles completable
where card.id = completable.review_card_id;

with completable_cycles as (
    select cycle.id
    from review_cycles cycle
    where cycle.status = 'IN_PROGRESS'
      and cycle.successful_review_count - cycle.failed_review_count >= cycle.target_success_count
      and exists (
          select 1
          from review_cycle_questions question
          where question.review_cycle_id = cycle.id
            and question.question_role = 'ORIGINAL'
      )
      and not exists (
          select 1
          from review_cycle_questions question
          where question.review_cycle_id = cycle.id
            and (
                (question.question_role = 'ORIGINAL' and question.review_status <> 'PASSED')
                or question.review_status in ('PENDING', 'RETRY')
            )
      )
)
update review_cycles cycle
set status = 'COMPLETED',
    completed_at = current_timestamp,
    updated_at = current_timestamp
from completable_cycles completable
where cycle.id = completable.id;

with eligible_errors as (
    select answer_error.*
    from user_answer_errors answer_error
    inner join user_answers user_answer
        on user_answer.id = answer_error.user_answer_id
       and user_answer.deleted = false
    inner join questions question
        on question.id = answer_error.question_id
       and question.enabled = true
       and question.deleted = false
    where answer_error.user_error_type_id is not null
), inserted_cards as (
    insert into review_cards (
        user_id,
        user_error_type_id,
        status,
        ease_factor,
        repetition_count,
        interval_days,
        lapse_count,
        due_at,
        last_reviewed_at,
        mastered_at,
        created_at,
        updated_at
    )
    select
        user_error_type.user_id,
        user_error_type.id,
        'ACTIVE',
        2.5000,
        0,
        1,
        0,
        (max(answer_error.created_at)::date + 1) + time '07:00',
        null,
        null,
        current_timestamp,
        current_timestamp
    from user_error_types user_error_type
    inner join eligible_errors answer_error
        on answer_error.user_error_type_id = user_error_type.id
    where user_error_type.status = 'ACTIVE'
    group by user_error_type.id, user_error_type.user_id
    on conflict (user_error_type_id) do nothing
    returning id, user_error_type_id
), inserted_cycles as (
    insert into review_cycles (
        review_card_id,
        cycle_no,
        status,
        target_success_count,
        successful_review_count,
        failed_review_count,
        verification_required_after,
        started_at,
        completed_at,
        created_at,
        updated_at
    )
    select
        inserted_card.id,
        1,
        'IN_PROGRESS',
        4,
        0,
        0,
        max(answer_error.created_at),
        current_timestamp,
        null,
        current_timestamp,
        current_timestamp
    from inserted_cards inserted_card
    inner join eligible_errors answer_error
        on answer_error.user_error_type_id = inserted_card.user_error_type_id
    group by inserted_card.id
    returning id, review_card_id
), source_questions as (
    select
        answer_error.user_error_type_id,
        answer_error.question_id,
        min(answer_error.created_at) as first_error_at
    from eligible_errors answer_error
    group by answer_error.user_error_type_id, answer_error.question_id
)
insert into review_cycle_questions (
    review_cycle_id,
    question_id,
    question_role,
    review_status,
    attempt_count,
    last_quality,
    last_attempt_at,
    passed_at,
    sort_order,
    created_at,
    updated_at
)
select
    inserted_cycle.id,
    source_question.question_id,
    'ORIGINAL',
    'PENDING',
    0,
    null,
    null,
    null,
    (row_number() over (
        partition by inserted_cycle.id
        order by source_question.first_error_at, source_question.question_id
    ) - 1)::integer,
    current_timestamp,
    current_timestamp
from inserted_cycles inserted_cycle
inner join inserted_cards inserted_card
    on inserted_card.id = inserted_cycle.review_card_id
inner join source_questions source_question
    on source_question.user_error_type_id = inserted_card.user_error_type_id
on conflict (review_cycle_id, question_id) do nothing;

create table if not exists tatoeba_candidates (
    id bigserial primary key,
    zh_sentence_id bigint not null,
    original_source_text text not null,
    raw_answers jsonb not null,
    completed_question jsonb,
    status varchar(32) not null default 'UNPROCESSED',
    question_id bigint references questions(id),
    last_error text,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_tatoeba_candidates_zh_sentence_id unique (zh_sentence_id),
    constraint uk_tatoeba_candidates_question_id unique (question_id),
    constraint ck_tatoeba_candidates_zh_sentence_id check (zh_sentence_id > 0),
    constraint ck_tatoeba_candidates_raw_answers check (
        jsonb_typeof(raw_answers) = 'array' and jsonb_array_length(raw_answers) > 0
    ),
    constraint ck_tatoeba_candidates_completed_question check (
        completed_question is null or jsonb_typeof(completed_question) = 'object'
    ),
    constraint ck_tatoeba_candidates_status check (
        status in ('UNPROCESSED', 'COMPLETED', 'COMPLETION_FAILED', 'IMPORTED')
    )
);

comment on table tatoeba_candidates is 'Tatoeba中日语料候选表';
comment on column tatoeba_candidates.id is '候选记录主键ID';
comment on column tatoeba_candidates.zh_sentence_id is 'Tatoeba中文句子ID';
comment on column tatoeba_candidates.original_source_text is 'Tatoeba原始中文句子';
comment on column tatoeba_candidates.raw_answers is '同一中文句子对应的原始日文译文数组';
comment on column tatoeba_candidates.completed_question is 'AI补全后的题目JSON，结构与AI生题的单题JSON一致';
comment on column tatoeba_candidates.status is '处理状态：UNPROCESSED=未处理，COMPLETED=已补全，COMPLETION_FAILED=补全校验失败，IMPORTED=已入库';
comment on column tatoeba_candidates.question_id is '正式入库后的题目ID';
comment on column tatoeba_candidates.last_error is '最近一次处理错误';

create index if not exists idx_tatoeba_candidates_status_id
    on tatoeba_candidates (status, id);
